### ISSUE TITLE
Separate initial liquidity from market proposals

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1047]
It may be better to separate market proposal from the initial liquidity provision since the parties that hold governance token may not be the same as the parties that hold the settlement asset. 

After this change it may be possible to propose a market and have it accepted without any liquidity committed; such a market will sit in an opening auction (extended possibly indefinitely due to lack of liquidity) until some is committed.

**Comment by barnabee** [comment]
> (extended possibly indefinitely due to lack of liquidity
I think there is a net param for how long a market can sit in an opening auction before it'll be unceremoniously ended 

Otherwise yes, agree, we should should do this as community members with a decent chunk of tokens could then propose a market without having to also be willing to be an LP, which may require a different skill set or be otherwise difficult for them.

If we do this we should remove LP commitments from the proposal txn entirely to simplify things rather than omit or change check for the committed amount. The only way to become an LP would then be the normal LP txn.
