### ISSUE TITLE
Capping slippage component of margin

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1581]
At the moment it seems that an order book with unreliable buys / sells can lead to undesirable closeouts getting triggered (@Jiajia-Cui is confirming with a feature test which we can review and then update to check we really have a fix). 

The reason is the slippage component of the margin (see also https://github.com/vegaprotocol/specs/issues/1567). 

Imagine a party A that's short 1 ETHUSD. If the buys sells are 
```
buy 1 @ 15000 
buy 10 @ 14900 
and
sell 1 @ 16000
sell 10 @ 16100 
```

then, if the last mark price was `15900` then the slippage charge is `16000 - 15900 = 100` (because to close the party out I need to execute a network trade on behalf of the distressed party, that would take its position to `0` i.e. the network needs to buy `1` so I need to compare to the price for selling `1` unit. The RF part is probably something like `15900 x 0.1 = 1590` so the slippage part is modest component of the maintenance margin. So far so good (or at least no disaster). 

Now imagine the book becomes: 
```
buy 1 @ 15000 
buy 10 @ 14900 
and
sell 1 @ 100 000
sell 10 @ 100 100 
```

The slippage is now `100 000 - 15900 = 84 100` which is a *lot* and will most likely initiate a closeout, draining the party's general and margin accounts (and bond if they happen to be an LP). 

So far this is the problem description. 

## Proposed solution 

I think we'd want both. 

### Cap the slippage component

Introduce a new optional market parameter `market.maxSlippageFraction` with default of `0.1` i.e. `10%`. The slippage component will never be allowed to be more that `min(slippage from book, market.maxSlippageFraction x size x mark price)`. 

The spec change PR for this is: https://github.com/vegaprotocol/specs/pull/1583

### Do not execute closeout trades that would reach volume too far out

Here, too far out would be IMO: 
1. volume outside price monitoring bounds 
1. volume outside LP liquidity range `market.liquidity.priceRange`.

**Comment by witgaw** [comment]
I'd just execute the closeout trade with a limit order placed at the price monitoring bound (so as to not trigger the price monitoring auction) and reduce the distressed parties positions pro rata from the sourced volume. 

If someone builds a huge positions relative to the market then masking it with 10% slippage may be dangerous should they  become distressed later on due to MTM losses.

**Comment by davidsiska-vega** [comment]
> If someone builds a huge positions relative to the market then masking it with 10% slippage 
1. I still think it's less bad than closing someone randomly because there is only crazy priced volume on the book for whatever reason (ddos attack so LP can't post or whatever). 
1. You're not exactly masking it because it's still at least `market.maxSlippageFraction x size x mark price + rf x size x mark price`. Finally it's up to the market creator, they can set `market.maxSlippageFraction  = 200%` or whatever if they want.

**Comment by davidsiska-vega** [comment]
If we go with "Do not execute closeout trades that would reach volume too far out" then we should probably start splitting closeout trades. So at each MTM:
- if a party is below maintenance close what you can that won't go past price monitoring / LP bound and confiscate margin balance. 

Note that if the position is e.g. 100 and the margin is subsequently 100 x rf x price (so say 160 000) if rf = 0.1 and price is 16 000 then most of it will go into the insurance pool. So if in the first round you can only close out e.g. 10 then most of the 160 000 will go into the insurance pool and will be available for subsequent closeout rounds (but the original party's margin is unlikely to amount to much unless MTM or gains on other markets fed it).

**Comment by barnabee** [comment]
I’m comfortable with capping and splitting close out volume as long as we do still try to close the rest out later if it’s still distressed, and there’s a way to tell there are pending close out orders/trades via some API so people can supply the liquidation demand (at a potentially very good price for them).

I’m not sure a passive limit order works for this though, perhaps unless we can guarantee the market is always in an auction if we have pending closeouts, as it could otherwise mean that all closeouts that happen like this get closed at the worst “allowable” price. Perhaps always being in an auction in this situation wouldn’t be a bad thing though?
