### ISSUE TITLE
Margin Isolation

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1627]
One of the processes that creates lots of data is the searching for margin. This issue is to start discussions around how margin may be able to be Segregated/separated in order to reduce the number of times the protocol needs to search for margin thus reducing the amount of data being created and stored.

In addition to the data creation point above there has been user feedback:
- users want to be able to segregate margin to guarantee maximum leverage / margin at risk relative to position notional (not currently possible in the presence of margin-bearing active orders)
- users should not have to pay fees to manage segregated margin and control leverage, however transfers require fees due to anti spam

This spec update should account for these too.

**Comment by davidsiska-vega** [comment]
@barnabee / @jeremyletang Note that a "tactical" optimisation we could do here is to simply have lower search level, higher initial margin and higher release level. This won't need any code change (and is just a stopgap).

**Comment by barnabee** [comment]
@gordsport worth updating the issue maybe that this also has user feedback/requirements as well as perofrmance advantage:

- users want to be able to segregate margin to guarantee maximum leverage / margin at risk relative to position notional (not currently possible in the presence of margin-bearing active orders)
- users should not have to pay fees to manage segregated margin and control leverage, however transfers reuqire fees due to anti spam

So we will build something into the protocol for this, for which I will provide a draft spec.
