### ISSUE TITLE
Perps: specify all data required by front-end in the spec

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#1849]
- Funding payment
- Funding rate
- Mark price TWAP
- Spot price TWAP

**Comment by JonRay15** [comment]
Main comments:

1. Are all of these on the API which will output the actual time series data?  ie. we'd get a funding event with a timestamp and then get all of the above fields?
2. I assume Spot Price TWAP is the price on the ethereum oracle?
3. Presumably there is also a funding frequency defined on some other API?  The market data one? Where are we capturing those requirements?  I would think they'd also be in the main perps spec right?

**Comment by mattrussell36** [comment]
> Main comments:
> 
>     1. Are all of these on the API which will output the actual time series data?  ie. we'd get a funding event with a timestamp and then get all of the above fields?
> 
>     2. I assume Spot Price TWAP is the price on the ethereum oracle?
> 
>     3. Presumably there is also a funding frequency defined on some other API?  The market data one? Where are we capturing those requirements?  I would think they'd also be in the main perps spec right?

1. Looks like current API changes give us all that data, query-able by date range and paginated. Which will allow us to build the funding history view
2. Not sure
3. Yes funding frequency is defined in the data source spec I believe, though it doesn't look like there is a PR to expose its values yet. We will aboslutely need that

**Comment by mattrussell36** [comment]
The two main bits of UI we need to build are, the market header and a funding history view

#### Market header

Something like:
![Screenshot 2023-08-09 at 12 03 55](https://github.com/vegaprotocol/specs/assets/6803987/d73fcd57-5db7-4e80-9fa3-6243d0895582)

Its important to note here that (I've been told) the current APIs will only show the rate/endtime data once the funding period is over (I believe this is a core restraint and not datanode). We need to ensure that we can show the endtime/rate for the _current_ funding period.

- Funding settlement time/countdown.
  - As mentioned in my previous comment we will need the funding frequency exposed in the APIs. In order to calculate the ending time of the period. Its captured [here](https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/data/v1/spec.proto#L73) in the protos but I don't see it in API changes. We need it added to the data source specs, or directly in the perpetual market object (`type Perpetual`)
- Funding rate
  - Like `endTime` this won't be updated until the period is over. Ideally the current funding rate would be exposed by the market data query/subscription so that the UI can be kept up to date. It can be null if the market is not a perp.

#### Funding history

Looks like this is already covered in already merged API changes. Currently we'd be able to display a funding history table with the following fields:

- start time
- end time
- funding rate
- funding payment
- external twap
- internal twap

**Comment by JonRay15** [comment]
Further to Matt's point above ... in a previous [thread](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1690979810488979?thread_ts=1690386098.034189&cid=C8WS7M50E) we seemed to have reached the conclusion that "every time a data point is received we want to calculate the funding rate at the time, and then shoot that data out? I think thats fine, and I thought we already added the twap’s to the event but I guess that technically isn’t the actual funding rate".

So I would think either:
- The current API needs to contain data for every oracle event and provide all values (which would therefore be much more data than just providing it at each funding)
- Some other API needs to provide all the above values every oracle event so this doesnt muddy the historic view of funding data (which realistically shouldnt care about the movements in between actual funding payments).

Option 2 seems more workable to me .. but I am not an API designer ... 😹

**Comment by JonRay15** [comment]
Three parts to this 

**First: The current latest value of funding rate** 

This needs to be calculated every time an event from the oracle is received
It needs to be made available somewhere (Core to determine where)

**Second: The time to the next settlement**
- The data source spec needs to include the settlement frequency & duration
- Console can then use the end time of the previous funding rate plus that frequency to determine the next funding event, or they could use the very first funding and keep incrementing by the duration in perpetuity.

**Third: The historical data for each actual funding event**

This is all given above in Matt's comment and sounds like it is already fine.  We need all of the below paginated so we can filter for time periods as appropriate. 
- start time
- end time
- funding rate
- funding payment
- external twap
- internal twap

**Comment by JonRay15** [comment]
Are these changes in PR for the spec yet?

**Comment by witgaw** [comment]
Closed by https://github.com/vegaprotocol/specs/pull/1907
