### ISSUE TITLE
Add governance action to early exit of price monitoring auction and trigger to enter an infinite length auction 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2192]
Add governance action to early exit of price monitoring auction and trigger to enter an infinite length auction.

- governance action to early exit of price monitoring should include new bounds that will be validated (i.e exit early but only if within those bounds).

**Comment by davidsiska-vega** [comment]
@witgaw Is doing a test to what extent this can be achieved by a two proposal batch which first removes most triggers and then reinstates them.

**Comment by witgaw** [comment]
The test is here: https://github.com/vegaprotocol/vega/blob/develop/core/integration/features/price_monitoring/end-long-auction-with-trigger-change.feature

Since early exit or extremely long auction can be achieved with the marke update transaction and an appropriate choice of triggers I'd suggest we close the issue.
