### ISSUE TITLE
Fix margin issue causing inability to close out a position

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#223]
In GitLab by @tamlyn10 on Mar 9, 2020, 16:49

As per @EVODelavega slack message: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1583754080036300

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 9, 2020, 16:51

changed title from **Fix {-issue with-} inability to close out a position** to **Fix {+margin issue causing+} inability to close out a position**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 9, 2020, 16:51

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 9, 2020, 16:51

assigned to @tamlyn10

**Comment by tamlyn10** [comment]
@barnabee I went looking for issues pertaining to the conversation we had yesterday about margins and found this one - see Slack thread above, raised by Elias.

@davidsiska-vega - Barney and I have noticed the behaviour whereby attempting to close out an existing position results in an order rejection. Clearly that's not ideal.

There are a few things at play:

1. Checking margins on whole portfolio when a new order is submitted means traders keep getting their margin requirement bumped back up to IM.
2. Liquidity orders are going to go through the "new order" check every time they are repriced.
3. Our current margin calculator DOES NOT calculate margin on "worst long" or "worst short" volume - it uses all orders and all open positions. 

Since we're thinking about margins, may be worth revising our memory on these issues too:

## update check order allocate margin for non-persistent orders that will trade
https://github.com/vegaprotocol/product/issues/163

## update margin spec for low liquidity
https://github.com/vegaprotocol/product/issues/224

**Comment by davidsiska-vega** [comment]
First step would be to create a cucumber test that can reproduce this behaviour.

**Comment by tamlyn10** [comment]
@EVODelavega @davidsiska-vega to confirm this has been addressed.

**Comment by edd** [comment]
@EVODelavega is this fixed?

**Comment by davidsiska-vega** [comment]
please check and close if possible @EVODelavega

**Comment by davidsiska-vega** [comment]
please check and close if possible @EVODelavega

**Comment by EVODelavega** [comment]
@edd @davidsiska-vega @tamlyn10 @ashleyvega  This issue was fixed a while back. A couple of weeks ago, I added the feature test `2878-close-out-orders-allowed-when-under-initial.feature` to ensure that it doesn't pop up without anyone noticing either. Closing this ticket.
