### ISSUE TITLE
Charging margins during auctions

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#325]
See discussions here: 
https://github.com/vegaprotocol/vega/issues/2042
https://github.com/vegaprotocol/vega/pull/2040

We need to spec:

## Opening auctions
* How is margin charged on new orders?

## Price monitoring auctions
* How is margin charged on new orders and existing positions?

**Comment by davidsiska-vega** [comment]
For opening auctions there will be no existing positions but for other auctions we would need to take existing positions into account as we do when determining margin for continuous trading.

@barnabee @tamlyn10 I think we will not do closeout trades during auctions price monitoring auctions.

I would suggest that during auctions we take the slippage component of the existing position to be 0 for margin calculation... another option below. The advantage is that we get more orders placed during the auction... disadvantage is that immediately after auction ends we may end up closing people out because the slippage kicks in...

Possible solution would be to track e.g. maximum slippage over a window for positions of size (1, 2, 4, 8, 16, 32, 64, 128) and then apply this slippage... (incidentally this may be used as well to keep the maintenance margin more stable during continuous trading).

**Comment by barnabee** [comment]
@davidsiska-vega yeah, I agree no closeouts can occur during auctions

Feels like the simple thing is to mark to market to the indicative uncrossing price only (as you suggest, no slippage component) and do collateral *searches but not releases* during the auction. 

The improvement would be to also evaluate the slippage as it would be if the auction ended now but with a slippage ceiling at the price monitoring point that would be in place (makes sense to me because there could be thin liquidity but the auction isn't going to end with such thin liquidity given liquidity monitoring).

**Comment by EVODelavega** [comment]
At some point in the past we'd mentioned calculating the margin based on the order price. That's what I've implemented for opening auctions, seeing as there's no mark price to start with. For FBA's and auctions triggered by liquidity/price monitoring, it'll be slightly different, but for opening auctions I'd argue that a trader should be able to put up the collateral to cover their trades at the price they set. This makes it quite easy to implement, and ensures traders will have sufficient margin at the end of the auction, so we don't start continuous trading with a bunch of parties being closed out.

**Comment by barnabee** [comment]
Yes I think for opening auctions the margin required *on entry of the order* should be based on order price.

The above discussion relates to **existing positions** that need to be re-evaluated _during the auction_ and may involve a collateral search (but IMO not release, and no closeouts) during the auction, based on the indicative uncrossing price.

@davidsiska-vega @tamlyn10 is this how you see it?

**Comment by davidsiska-vega** [comment]
For opening auctions: the market observable for futures should come from the price from the order as @EVODelavega says. 

For price monitoring auctions: for orders placed during auction use the same as above. For margin required for existing positions we need to decide how to deal with slippage. There are two extremes:
1) count 0 slippage. Advantage: more orders can be placed during auctions as there are fewer margin constraints. Disadvantage: possible closeouts when auction ends and traders' margin situation gets re-evaluated. 
2) assume slippage is all the way to the price monitoring trigger. Advantage: no unexpected closeouts at auction end as everyone will have to hold more margin. Disadvantage: traders will likely be only able to place orders that reduce their position
3) a version of 2 above that uses the orders placed during the auction to estimate slippage and maxes out at price monitoring trigger. This is a bit more capital efficient for traders than option 2) 
4) keep track of maximum slippage for various position sizes over a window of time and use that for open positions during auctions to account for slippage. Advantage: capital efficient but shouldn't lead to closeouts at auction end. Disadvantage: more development needed, I wouldn't advocate this for current Testnet pipeline.

Conclusion: I support what @EVODelavega has for opening auction and agree with @barnabee that we should go with 3) above for existing positions. I also agree that we should top up margin account from general account but we shouldn't release during auctions.

**Comment by barnabee** [comment]
@davidsiska-vega cool, do you think it makes sense per my first comment to do the simple version — only mark to market to the indicative uncrossing price and assume no additional slippage, for the first version of this or would you like to incorporate your option 3 from the start?

**Comment by tamlyn10** [comment]
@davidsiska-vega in 3) when you say the price monitoring trigger - do you mean the level as set going into the auction?

also, presume this is the case for all non-opening auctions (not just price monitoring)?

**Comment by tamlyn10** [comment]
@barnabee I agree with this: _may involve a collateral search (but IMO not release, and no closeouts) during the auction_

**Comment by EVODelavega** [comment]
Just to be clear abou tthis: @tamlyn10 mentioned that we should still calculate margin requirements based on the max long/short positions, but use the order price. That's all well and good, but it makes it so I can easily release much of my collateral during an auction:

Put in orders at a high price, and at the end, put in 1 order that increases my _"most liable position"_ (ie max margin long -> put in a buy order, max margin short, but in a sell order) at a ridiculous price. The margin is recalculated using this new price, and my collateral is many times over the release level as a result. I'm going to end up with a ridiculous margin.

For that reason, we're currently calculating margin requirements per order, and allocating margin for each order. If an order is cancelled or amended, we know exactly how much margin was allocated to begin with, and we can release the same amount, keeping every active order on the book covered. Once the opening auction ends, the positions are market to market in full, and the margin balances are recalculated using the same approach we currently have.

**Comment by davidsiska-vega** [comment]
@barnabee I think that initially we should implement the simplest version. But I am just checking that I understand what you mean by the "mark-to-market". 

If in continuous trading I have an open position (say 10 long and no orders) my maintenance_margin = "slippage to close a position of size 10"  + 10 x mark_price x RF_long. 

Now I am in auction mode, the network won't try to close me out, won't release any collateral but may try to top me up...

We don't do any mark-to-market transfers during the auction. So let's say that before the auction started the mark price was 120. Now the indicative uncrossing price is 90. My maintenance margin calculation will be:

maintenance_margin = "mark to market move of 30" x 10 + 10 x "indicative uncrossing price" x RF_long. 

If the network can transfer from general to margin to meet this (at search level) it will. If it cannot it will not do anything. It won't try to release.

**Comment by tamlyn10** [comment]
@EVODelavega 

I assumed it would use a volume weighted price of all your buy orders..

**Comment by tamlyn10** [comment]
@davidsiska-vega that is my understanding, and what I was thinking when I proposed using indicative uncrossing price.

**Comment by barnabee** [comment]
@davidsiska-vega yes, that's what I mean, we can do or not the MTM transfers (I have no opinion) based on the indicative uncrossing price but the key is if we would normally do a search for a given position if the mark price == indicative uncrossing price than we do the search during the auction too (but no release) to minimise chance you owe tons unexpectedly on auction close.

@tamlyn10 I don't really understand what you are suggesting... I have assumed we do a *one off* transfer for each new order entering the book but I am not sure exactly how we calculate this...?

Maybe we should see if the order increases your "net worst" long/short position (I think we already calculate this for positions?) and if it does do a transfer of the margin amount that would be required for the increase in net worst position, assuming mark price = ?? [the price of the order?] 

What did you have in mind? I'm not all that sure about the above approach I outlined, more a thought experiment, possibly not a useful one...

🤷‍♂️

**Comment by EVODelavega** [comment]
So just so we're clear:

* Opening auctions: Orders result in a one-off transfer to the margin account based on size & price of that order. This ensures the trader has sufficient collateral should their order get uncrossed at the end of the auction, always

* Other auctions: Use last known mark price as a base line, perhaps use indicative price, use highest margin that applies?

I'm not entirely clear what the price is we ought to use for auctions, other than opening auctions, but right now, we've got an implementation of margin calculation for opening auctions ready. It'd be nice to know whether or not that implementation is correct/acceptable.
Using the volume weighted average price is something we don't have ready ATM, and in case of opening auctions, there's not going to be a mark price or an indicative price for the first orders until there is a matching pair of orders on the book anyway.

If one-off margins per order for opening auctions are acceptable, I'd argue that this is the quickest way to get, what to me looks like a decent compromise, in the system.

@barnabee @tamlyn10 @davidsiska-vega

**Comment by tamlyn10** [comment]
@EVODelavega how do one-off margins for orders work? To use your example from the other discussion..

Trader: 
1. submits order1 size +100, price 1,000,000
1. submits order2 size +1, price 10

I would expect: 
1. After first order, the margin maintenance is 100x1,000,000xrf_long and the transfer is for the initial margin amount
1. After second order, the margin maintenance is 101xvol-wted-pricexrf_long = 101x((1x10+100x1,000,000)/101)xrf_long. However, this is equivalent to simply adding 1x10xrf_long, so I'd expect the transfer is for the IM-scaling-factorx1x10xrf_long.

Is thsi what you mean by one-off margins?

**Comment by tamlyn10** [comment]
A further note on this, we should, of course, be comparing these buy order margins to any sell order margins and making sure we are taking the maximum of the two (as per current spec)

**Comment by tamlyn10** [comment]
@barnabee since opening auctions are all about orders, only.. any new order is increasing the "net worst" long or short position, since: ```riskiest long = max( open_volume + buy_orders , 0 )```

Important to note, however, that the margin equation in the spec doesn't actually use the net-worst-position-size as an input:

```maintenance_margin_long = max(slippage_volume * slippage_per_unit, 0) + slippage_volume * [ quantitative_model.risk_factors_long ] . [ Product.market_observables ] + buy_orders * [ quantitative_model.risk_factors_long ] . [ Product.market_observables ] ,``` 

where

```slippage_volume = max( open_volume, 0 ) ```

**Comment by EVODelavega** [comment]
The risk calculations you mention is a volume weighted average price. We just don't have the information required to hand to calculate that for each new order. The result is that the margin balances during an opening auction will just linearly increase per order placed. The upshot is: we don't have to recalculate a volume weighted price every time an order is amended or cancelled, we can just recalculate the margin allocated for the order in question, and release that amount immediately. It's the quickest way to ensure there's enough margin for each and every individual order placed, without having to rework other parts of the core

We're also not looking at net worst for opening auctions. If someone has a max worst long of, say, 1000, and a short for 1001, by how much do we increase the balance if a buy order is placed? What if that buy order is placed, but an order gets amended/cancelled? We'd have to work out the full position again, the price, and then work out what portion of the margin should be released. With the current implementation, a trader with both buy and sell orders most likely will end up with a margin that is above the release level as soon as the auction ends, but I think that's reasonable, given that overestimating the collateral requirements during an auction (for example triggered by price margin) is less likely to have an auction period end with a ton of traders in distressed states, triggering a second auction because of liquidity/price monitoring issues.

**Comment by barnabee** [comment]
> @barnabee since opening auctions are all about orders, only.. any new order is increasing the "net worst" long or short position, since: riskiest long = max( open_volume + buy_orders , 0 )

Regardless of whether it's an opening auction or another type we need to do something when a new order is received, before it's allowed on the book (i.e. we need to make sure https://github.com/vegaprotocol/product/blob/master/specs/0011-check-order-allocate-margin.md works in an auction, I thought by using the limit price of the order rather than the mark price as the margin calc input...), and something after placing it on the book and calculating the indicative uncrossing price, i.e. making sure https://github.com/vegaprotocol/product/blob/master/specs/0019-margin-calculator.md works in an auction, I thought by using the indicative uncrossing price instead of the mark price as the margin calc input, and disabling collateral release and closeouts) I'm not sure why it would be special for opening auctions so I don't follow this line of reasoning. 

I don't really understand what's happening in this thread. It seems like half a discussion about this way and half a separate discussion about something specific and different for opening auctions. IMO there should be _one way margins work in auctions_ which I would work for both cases, unless we prove together and agree that's not going to work. 

As much as we can we should also use the existing logic/structure/thinking for how margins work on new orders and when doing MTM for auctions and continuous trading. In the ideal world we are just swapping out inputs (i.e. taking the order's price instead of something or using indicative uncrossing price instead of mark price, etc. rather than using a new calc.

My assumption is we calculate margin deltas:

1. **[on entry, before adding the order to the book]** calculating how much (if any) additional margin to transfer for the party entering a new order into the auction, based on the price they have provided for that order but using the existing logic for new orders coming in, i.e.:
- if this increases their riskiest long/short and that translates to an increased margin requirement, I'd expect us to add some margin to cover it (exactly as per the existing spec); and in that case _I thought we were saying we could just use the order's price and size to calculate a margin amount for that order_ (is this correct/will it work? I am not sure where the volume weighted reevaluation of the whole position discussed above is coming from or why it might be necessary?) — this seems like it makes sense for opening and other auctions if we can agree the calc

2. **[after adding the order to the book]** calculating an MTM move for all open positions after adding a new order to the book, based on the indicative uncrossing price rather than mark price, and transferring additional margin where possible if any positions are below the search level — this is fine in an opening auction because everyone's open position is zero so there's nothing to do, it does not therefore need to be a special case

What am I missing here? Is there a reason we need to design this separately for opening and other auctions and create that complexity? I currently don't see it.


@tamlyn10 I also don't understand this:

> Important to note, however, that the margin equation in the spec doesn't actually use the net-worst-position-size as an input:

The overall algortithm does use it, which I assume means it must be calculated and is available to the core, which is all I said. (The first part of steps 1 and 2 [here](https://github.com/vegaprotocol/product/blob/master/specs/0019-margin-calculator.md) directly uses the riskiest long and riskiest short values as an input.)

**Comment by barnabee** [comment]
It may be that we need a call on this, if we feel it has become confused. I am not sure how much I follow all the thread at this point...

**Comment by tamlyn10** [comment]
@barnabee just for context, the vol-wted price thing I brought up [here](https://github.com/vegaprotocol/vega/pull/2040), to counter the idea of using the **last order** price as the market observable for the margin calculation.

The point was if you want to use an order price for the "market observable" in the current margin calculator, then it needs to be the vol-wted price. If you simply add each new order's incurred margin where market-observable-for-that-order = order-price, to the previous margin requirement that's also fine in this case (see my spreadsheet attached). 
[simple-new-orders.xlsx](https://github.com/vegaprotocol/product/files/5002585/simple-new-orders.xlsx)

**Comment by tamlyn10** [comment]
Happy to do a call.. and agree with your sentiment around having consistency btw!

**Comment by barnabee** [comment]
Thanks @tamlyn10 that is heplful. @EVODelavega please feel free to set up a call to finalise this.
