### ISSUE TITLE
Single party open position is more than available book volume

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#348]
This is an analysis ticket to consider how we expect Vega to behave in the following situation *given the current specs around liquidity*:
1. A party has blown their margin, we cancelled their open orders and now
1. Said party open position is more than available book volume 

What do we expect will happen? Can we prove that 2. is impossible with current specs? @tamlyn10 @barnabee @witgaw

**Comment by witgaw** [comment]
I think the current approach is we just leave it there and attempt a (full) closeout next time around. Why would 2 be impossible? All the orders can just get cancelled at once without moving the mark price.

**Comment by barnabee** [comment]
@witgaw impossible becasue you'd be in a liqudity monitoring auction before you get there

It's definitely true that in some, probably many cases it's impossible because the relationship between open interest (the open position mentioned is always ≤ open interest in size, by definition),  liqudiity stake/commitments, and the triggers for a liquidity auction would mean that you're in an auction first because the required liquidity provision not to be would always more than cover the order in poiint 2 above. But is that guaranteed or are there values for the network parameters around liquidity demand calculation, stake<>liqudity, and auction triggers that would make point 2 possible.... seems to me like it could be possible if you had low enough multipliers everywhere and high enough probabilities of trading…

If that's the case I guess we have to choose whether to:

- Set limits for the params to make it impossible
- Add an additional explicit trigger to make it impossible
- Drop that rule/mechanic

NB: in the white paper _"In the event that the buy or sell side of the order book volume is insufficient to close the largest single counter position held by a trader, the market will be suspended"_ was **the** liquidity monitoring mechanic, so there's an argument for the 3rd option that the original design has been superceded. We should update the WP with a better description of liquidity monitoring either way IMO.

**Comment by witgaw** [comment]
> @witgaw impossible becasue you'd be in a liqudity monitoring auction before you get there
> 
> It's definitely true that in some, probably many cases it's impossible because the relationship between open interest (the open position mentioned is always ≤ open interest in size, by definition), liqudiity stake/commitments, and the triggers for a liquidity auction would mean that you're in an auction first because the required liquidity provision not to be would always more than cover the order in poiint 2 above. But is that guaranteed or are there values for the network parameters around liquidity demand calculation, stake<>liqudity, and auction triggers that would make point 2 possible.... seems to me like it could be possible if you had low enough multipliers everywhere and high enough probabilities of trading…
> 
> If that's the case I guess we have to choose whether to:
> 
> * Set limits for the params to make it impossible
> * Add an additional explicit trigger to make it impossible
> * Drop that rule/mechanic
> 
> NB: in the white paper _"In the event that the buy or sell side of the order book volume is insufficient to close the largest single counter position held by a trader, the market will be suspended"_ was **the** liquidity monitoring mechanic, so there's an argument for the 3rd option that the original design has been superceded. We should update the WP with a better description of liquidity monitoring either way IMO.

Ah yes, thanks. I misinterpreted the "current specs" as what's currently implemented.

**Comment by davidsiska-vega** [comment]
My answer is that we cannot guarantee that 2 is prevented with current spec.
![image](https://user-images.githubusercontent.com/62546419/92750953-76568800-f37f-11ea-9160-e3aafdb49c7c.png)

**Comment by davidsiska-vega** [comment]
@tamlyn10 @barnabee Looking at the last formula on the page it seems to me that we want to have the value of open interest rather than open interest in units of volume, which is not in the `target-stake.md` at the moment but it's an easy fix if you agree. That way the units will make sense again (or the other possibility is I messed up somewhere).

**Comment by davidsiska-vega** [comment]
I think the correct fix is to actually change the closeout spec so that if we get to 2. then we close out as much volume as we can (and confiscate all the margin). If we cannot close anything then leave it.  

This party will then be in breach of margin (clearly) but the liquidity provider auto-refreshing order will put some volume on the book at the next opportunity. Then, when we come to evaluate the margin situation of this party again, we will be able to close out a bit more. Eventually either:
a) we closed the delinquent party out
b) liquidity provider is short of margin, means their stake gets moved to margin account, means that stake falls below target stake means we go into liquidity auction. This will eventually terminate if an LP commits stake and then Vega can go back at chipping away at that position.

**Comment by barnabee** [comment]
Hmm, trying to close as much volume as possible where we can't close it all ought to trigger liquidity monitoring without closing anything, shouldn't it?

In that case, trying to close as much as we can (IOC) rather than use an FOK ought to trigger a liquidity auction without closing anything, which actually would give us what we wanted originally, unless I'm missing something?

**Comment by davidsiska-vega** [comment]
@barnabee Not as it is specced currently.

**Comment by davidsiska-vega** [comment]
@barnabee the liquidity auction could end without providing enough volume if the risk factor or the other parameters are small enough.
