### ISSUE TITLE
Margin on orders in an opening auctions - what is the market observable for futures?

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#360]
Tamlyn  7 days ago
I think the answer is a little more complicated than that.
A buy and sell auction order does not necessarily mean there will be a trade (depends on their prices). If there is no trade, there is no open positions on the market, then we could open up a limit order book (liquidity monitoring and price monitoring wouldn’t apply). And there would be no attempt at mark to market settlement. However, orders incur margin and the thing I’m not sure we’ve accounted for is in continuous trading, how the margin orders are calculated if there is no mark price (we have covered this off for auctions.
I think we need a spec update to account for margin. 

~~I think that the margin for an order in auction should simply be size x risk factor x order price i.e. we use the price in the order for the market observable .
We can do it EITHER
i) for the entire auction duration OR
ii) only when there is no indicative uncrossing price (and with indicative uncrossing price we’ll use that)
@tamlyn10  I don’t suppose you have better memory than me of where this got to?~~

**Comment by davidsiska-vega** [comment]
@barnabee can you have a look at the proposed issue & solution here? If you agree that we can go ahead like this I'll amend the margin calculation spec (the auction part).

**Comment by tamlyn10** [comment]
@davidsiska-vega this issue is about margins on orders during LIMIT order trading, AFTER an opening auction, assuming there's been no mark price /  uncrossing.  

One way we could approach this is to not open into limit order book trading if there is no uncrossing. This would make sense to me, personally, but is not specced. 

The other way would be to figure out a way to compute margins during limit order trading using just order prices or an alternative price - like "mid price".. again, this may not exist. Consider a situation where there is only sell interest on a market, no buy interest. And NO TRADES during opening auction and only offers on the book. IMO this market should remain in auction.

Regarding your proposal about how to cover off margins on orders DURING auction, we have already covered this off in the margin spec (recently we all had a big chat and you kindly finished it off and merged it IIRC)

**Comment by davidsiska-vega** [comment]
Chatting with Tamlyn.
1) Margin on orders in auctions is covered, including opening opening auctions. 
2) If the opening auction doesn't result in a trade after the opening auction duration I propose we restart the auction with the same period and repeat this until there is a trade or until the market expires.

**Comment by barnabee** [comment]
For 2 of suggest we just make having at least one trade an ending criteria for the opening auction rather than restart it, we already extend if liquidity criteria aren’t met and I think these things will play better together if we simply have the opening auction last until we are ready to start trading, which given the above should include having had a trade.

**Comment by tamlyn10** [comment]
@barnabee that makes sense to me - I'll include in the market lifecycle (etc.) edits I'm currently doing.

**Comment by tamlyn10** [comment]
@barnabee actually, I don't think "one trade" is the right metric, given IIRC wash trading is permitted in version 1 of the auctions (cc @peterbarrow to confirm).

As such, I propose that the metric is that the market's open interest is greater than 0.

**Comment by davidsiska-vega** [comment]
Even a wash trade would be enough to set the mark price @tamlyn10 (though it may be completely unrepresentative). 

So perhaps it's enough? Though an open interest > 0 as you suggest might be better.

**Comment by tamlyn10** [comment]
yeah, so, also i'm wanting to avoid a graveyard of empty markets and with no open interest there's no liquidity requirements.. the book can remain empty indefinitely...

**Comment by davidsiska-vega** [comment]
Well I liked that it's got no liquidity requirement - at least this dead market isn't tying anyone's stake up.

**Comment by barnabee** [comment]
Hmm, if a market where OI drops to zero can remain open and liquidity committed is low then a trade could send it straight into liquidity auction… is that a problem? It's true at any other time that a single trade could so that anyway so I guess it's kinda OK? Perhaps if there's zero liquidity committed we should always be in a liquidity auction, as a basic backstop?

**Comment by barnabee** [comment]
And re: waiting for one trade, if the only issue is wash trading then let's prevent that in auctions? I'd suggest we simply reject any order placed into an auction that crosses with another of your orders, ie if it could trade with it, as to some extent everyone effectively trades with everyone else in an auction uncrossing, conceptually and it should be simple enough to implement and cheap to check by maintaining a best bid and offer price for each trader. 

I don't think we'd need this until after "n+2" though?

**Comment by tamlyn10** [comment]
- agree with only preventing wash trading in auction after "n+2"


- agree that zero liquidity committed should be in a liquidity auction. I still don't love that the market continues to live on, as we really wanted to design something where only liquid, good quality market get to use up Vega resources. I think an area of future thinking / analysis might be how a market gets gracefully wound down through market data triggers in addition to the governance vote.

**Comment by barnabee** [comment]
A market uses nearly no resources if noone is trading, whether in an auction or not (resource usage mostly = storing and processing transactions, so if there aren't any happening the usage is low), so it isn't a huge worry from a resource point of view, but I totally agree that longer term we should be able to close non-well-functioning markets. I am not sure if that can reasonably be done automatically though, I would guess possibly not.

We will allow a market to be voted to be closed (as a market parameter change) at some point, the only major thing preventing that when parameter change governance is added is that we'd need to write a spec for what happens to open positions if a market is voted to be closed (I referenced the need for this briefly in market framework), but a starting point could be to only allow closing a market with zero OI initially, though in practice that may not be a very useful start.

**Comment by davidsiska-vega** [comment]
@tamlyn10 I don't like that we will be "listing" a "dead" market (though we can have filters for markets with zero commitments in eg UI). But I wouldn't worry in terms of resources - a zero stake market isn't going to be generating much activity compared to a liquid active market. So I don't see why this will be a problem. 

Otherwise a simple solution is that a market that has ZERO stake a `network parameter` (eg week) after inception is removed.

**Comment by davidsiska-vega** [comment]
@barnabee you beat me to answering this by a whole minute ;-)

**Comment by tamlyn10** [comment]
haha you're both such engineers.. i'm talking about "trading attention" more than network bandwidth...

**Comment by davidsiska-vega** [comment]
But I covered trading attention - simply provide a tool that filters out stake=zero markets.

**Comment by barnabee** [comment]
@tamlyn10 trading attention = front end problem not protocol problem 😼

**Comment by tamlyn10** [comment]
Well.. what about the developer experience, then?

**Comment by barnabee** [comment]
How do you see this impacting developer experience? Doesn't change the code/effort for integrations, that I can see.

**Comment by tamlyn10** [comment]
I believe our specs are updated as per this discussion - @davidsiska-vega could you confirm and close if so?
