### ISSUE TITLE
Minimum liquidity provider stake commitment before market goes to opening auction

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#364]
What is the minimum stake a ~~market maker~~ liquidity provider must commit to a market before it's allowed to go into an opening auction? 
1. Zero? Then immediately after opening auction a liquidity auction will be triggered and maybe that's good enough?
2. Enough for `max_oi = 1` ie  `stake >=  v_for_target_stake x rf` (see `0041-target-stake.md`)? 
3. We add *another network parameter* something like "mimimum_viable_oi"  and say that `stake >=  mimimum_viable_oi x v_for_target_stake x rf`? 
4. Have per asset minimum stake (asset parameter) to launch a market. 

I like 1. for its simplicity as to me it seems we don't have to worry and just go with we've got in the protocol already. 

2. is OK but not so different from 1. since finally as soon as some meaningful trading happens we're likely to end up in a liquidity auction. 

3. is pointless in my opinion because markets can be proposed with one contract unit not having much value and so it could be gamed (in my mind) and it adds another network parameter (which should be avoided if possible). 

4. This is more thinking about avoiding a market proposal spam - if you need to commit some ~ 1 000 USD to launch a market you're going to be a bit serious about it. 

@barnabee @tamlyn10 @witgaw Please let's hear your thoughts and add conclusion to the market lifecycle spec.

**Comment by davidsiska-vega** [comment]
@edd this is the one you were asking me about on Slack yesterday evening, if I understood correctly.

**Comment by edd** [comment]
You're absolutely correct.  I think this belongs in the Market Lifecycle spec (https://github.com/vegaprotocol/product/pull/288 - status: @barnabee's work needs a review and probably some work) or the Target Stake spec (https://github.com/vegaprotocol/product/blob/master/specs/0041-target-stake.md). Probably the former. I *suspect* it's a relatively simple diagram that will link together these specs:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtNYXJrZXQgaXMgcHJvcG9zZWRdIC0tPiBCW1ZvdGluZyBiZWdpbnNdXG4gIEEgLS0-IENbU3Rha2luZyBsaXF1aWRpdHkgYmVnaW5zXVxuICBCIC0tPiBWW1ZvdGluZ1BlcmlvZENsb3Nlc11cbiAgQyAtLT4gVlxuICBWLS0-IER7RGlkIHRoZSB2b3RlIHBhc3N9XG4gIEQgLS0-fE5vfCBSZWplY3RlZFxuICBEIC0tPnxZZXN8IEV7SXMgdGhlcmUgZW5vdWdoIGxpcXVpZGl0eX1cdFxuICBFIC0tPnxOb3wgUmVqZWN0ZWRcbiAgRSAtLT58WWVzfCBuKFN1Y2Nlc3MpXHRcbiAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX19)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtNYXJrZXQgaXMgcHJvcG9zZWRdIC0tPiBCW1ZvdGluZyBiZWdpbnNdXG4gIEEgLS0-IENbU3Rha2luZyBsaXF1aWRpdHkgYmVnaW5zXVxuICBCIC0tPiBWW1ZvdGluZ1BlcmlvZENsb3Nlc11cbiAgQyAtLT4gVlxuICBWLS0-IER7RGlkIHRoZSB2b3RlIHBhc3N9XG4gIEQgLS0-fE5vfCBSZWplY3RlZFxuICBEIC0tPnxZZXN8IEV7SXMgdGhlcmUgZW5vdWdoIGxpcXVpZGl0eX1cdFxuICBFIC0tPnxOb3wgUmVqZWN0ZWRcbiAgRSAtLT58WWVzfCBuKFN1Y2Nlc3MpXHRcbiAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX19)

But that may not be correct.

**Comment by barnabee** [comment]
@edd the diagram is _nearly_ correct vs whitepaper, which allows a market which passes the vote to remain pending indefinitely (up to some cut off or the point the market would have expired).

@davidsiska-vega thanks, I think I agree with your analysis and also about 1 being the right option for simplicity. This has caused me to think about the lifecycle and also the spam point a bit, and I think we can refine and simplify:

This design was based on the idea of creating a target that must be reached to launch a market in order to gather support early for the market and also ensure the market [behaves well](https://vega.team/concepts/well-functioning-markets.html) on launch. Partly this was due to a less robust liquidity monitoring design in the WP, so it may be worth revisiting.

If we decide to stick with a target, it almost certainly needs to differ per asset, but also quite possibly per market. This is because you want a situation where the market would remain in normal trading under minimal but nonethesless meaningful trading volumes and price movement. Shoving in [another] network parameter per asset (option 4) would be the "MVP" of this but it's not convincing to me that this achieves the goal.

As @davidsiska-vega says, the other potentially sensible option is to do away with minimum liquidity stake for market launch. This is attractive because **the combination of an opening auction plus liqudiity monitoring already contains a mechanism to determine how much stake a market requires**. Realising this, it actually feels duplicative to do anything else. I think we should go with zero stake requirement.

This has me questioning the Pending market state (as described in the WP and [this WIP spec](https://github.com/vegaprotocol/product/blob/57839a9babeb494edee5bc74060f5be39a239d88/specs/0029%20-%20Market%20Lifecycle.md)) vs the opening auction. The pending state exists to (a) cover the time before the market should be trading; and (b) gather liquidity and determine if there is enough. These are both functions that the opening auction can perform, so I propose that as soon as the market hits the Pending state (i.e. voting close and vote passed), it _immediately_ enters an opening auction and remains there until the market creation/opening time is reached AND the criteria are satisfied such that it wouldn't open directly into a liquidity monitoring auction. 

Finally, on the subject of spam, there are two things I think it would make sense to do:

- Require a minimum number of governance tokens to make a [market creation] proposal and implement the previously discussed idea to lock (prevent withdrawal or use as trading margin) a participant's eligible governance tokens for the duration of the voting period. [I realise this is out of scope for this ticket and should be addressed in a future update to governance. I suspect we'll need it before Mainnet.]
- Implement a per asset minimum stake **for the proposer** as part of the asset "framework". This sounds a bit like option 4 above but it isn't. It isn't about how much a market needs committed to be useful, and would not be allowed to comprise commitments from many liquidity providers, instead it would simply be a mechanism to make our market making requirement filter useful. That is to say that the reason we require a liquidity provision commitment with each proposal is as a filter on market creation to those who have considered and are willing to support a market, and this doesn't work very well if you can commit 50 cents, so having a minimum stake that needs to go alongside a comitment, denominated per asset and changeable via network parameter governance would ensure this. [We could launch the feature in public Testnet without this.]

----

So to summarise, if David and Tamlyn agree with this thinking, I would suggest we do the following at a minimum:

- Lose the idea of a minimum stake to open the market (we'll rely on opening auction plus liquidity monitoring).
- Start the opening auction as soon as the vote closes (if it passes) to gather liqudiity and begin price determination.
- Open the market (uncross the auction) if there's enough liquidity to not be in liquidity monitoring at the enactment time, other wise stay in the opening auction until there is ∴ opening auction replaces Pending state.

Ideally we'd do this at the same time, but it could wait to get the first version of liquidity provision into Testnet quicker:

- Implement a per asset minimum liquidity commitment stake that applies **only** to liquidity committed with market creation proposals. (So yes, to some extent this is a minimum stake to open a market, but it actually says nothing about the liquidity needed to do so and is a filtering measure on proposals. It could safely be set to zero from a market functioning perspective.)

We should probably also raise a ticket if there isn't one to spec lockup of governance tokens and check if minimum token holding to create a proposal made it in, and add that too if not.

@tamlyn10 @davidsiska-vega, what do you think?

**Comment by davidsiska-vega** [comment]
I think that's good. I agree with per-asset minimum stake as a filter for market creation spam, disconnected from liquidity-requirement-implied minimum stake. 

Should the minimum stake to propose a market should go into `0028-governance.md` and `0001-market-framework.md`? @tamlyn10 

The only other thing I would consider is locking all the Vega tokens that voted to create a market for the duration of the market. I believe that this will incentivise more careful consideration, by Vega token holders, of which markets to support. By locking I mean disallowing them from participating in other market proposal votes. The motivation isn't to create token demand but rather to drive more scrutiny of market proposals.

**Comment by barnabee** [comment]
Awesome, thanks @davidsiska-vega!

I think locking for the duration of the market including from other governance votes might be too much. We want people to create multiple markets and also want them to participate in governance votes on other things.

We could consider locking them as I described, so they can’t be used as margin or withdrawn, but can be used for other votes, for the life of the market, but then what about markers that don’t expire ever?

I think just locking (with the definition I provided above — preventing withdrawal or use as margin but not preventing voting on other proposals) for the period of the vote works for me (and isn’t specced or planned yet), but happy to hear justifications for alternatives.

**Comment by davidsiska-vega** [comment]
Perpetual markets should probably only come after we've set up a mechanism for winding down a market pre-settlement if the liquidity providers no longer want to support it. So perpetual markets are not so much of an issue for me. 

My feeling is that if I vote for a market it should really be for one that I think will create revenue for Vega token holders (because there are costs associated to running markets). As for "wanting people to participate": well I don't have to support a market with all my tokens... 

But anyway I am not hell-bent on having Vega tokens locked up for duration and certainly *not important* right now, so let's forget that. Vega tokens are locked for duration of vote and that's it.

**Comment by barnabee** [comment]
This mechanic should be one we think has a reasonable chance of being product independent, assuming the the other things (risk model, liquidity monitoring, etc.) work, so I would rather not design something we need to revisit that soon. 

So yeah, locked (per my original definition: prevented from withdrawal/use as margin only) for duration of vote for all governance votes IMO is still the right answer for now. I assume we will probably decide we want it for WWN but we should be willing to decide if it is necessary for that or a nice to have. I am thinking the latter may be the case and we perhaps just put a high-ish threshold number of tokens to propose a market in WWN instead, to keep scope as minimal as possible for WWN. 

Either way: governance spec needs an update at some point in addition to the decisions above, so I made a ticket: https://github.com/vegaprotocol/product/issues/366

**Comment by tamlyn10** [comment]
OK, I've caught up on this now. So, I agree with most of your analysis and conclusions - one disagreement - see below.

1. Getting rid of proposal period - to be honest, I'd smooshed the "pending state" into the "voting period" in my head and so the immediate transition to auction mode is what I'd been assuming anyway. I'd also thought we may just not open the market if not enough liquidity committed - as per your suggestion @barnabee 

1. I think the per asset proposer's stake is good, agree iwth you there @davidsiska-vega 

1. I **don't like the locking of goverance tokens to be only able to vote on one market at a time. I** don't see the point of it, it's not consistent with the purpose of the token IMO, and it incentivises proposers to always nominate the shortest proposal period because people may not want to lock their tokens longer. I think it's confusing and begs the question of whether it's just market creation governance proposals or other types that you're prevented from then voting on? We're intending to build community norms around careful consideration of markets and this to me is a blunt attempt to achieve what we should be investing hard work into achieving through education etc.

**Comment by barnabee** [comment]
Ok so you're disagreeing with @davidsiska-vega and agreeing with me on the third point @tamlyn10? Or is there something I've suggested that you disagree with too? (I don't think so?)

**Comment by tamlyn10** [comment]
I think I fully agreed with you except where you agreed with David on that point about locking the vote tokens to a proposal 😸

**Comment by barnabee** [comment]
I [disagreed](https://github.com/vegaprotocol/product/issues/364#issuecomment-701495195) with @davidsiska-vega on that, so I think we're in agreement but I can see that it's a bit ambiguous in the later comments where I say locked which definition I am talking about.

I am still arguing for and stand by my definition of locking from my first comment, i.e. "prevent withdrawal or use as trading margin", I still agree with my (and your) reasons for not limiting these governance tokens use for voting in other proposals. It also has the danger that all the "good" voters could by locked in other votes and a "bad" proposal could slip through. Nope. 

I have edited my latter comments where I use the term "lock" to be explicit that I am still proposing my original definition.

**Comment by barnabee** [comment]
On a conceptual note, the way that I think of "locking" or "committing" tokens to a vote is that it is intended to prevent _moving/transferring_ them, i.e. taking actions that would stop them being counted towards your vote, and creates an opportunity cost hurdle, but that it should not impact their _functionality_ (i.e. voting, delegating, and staking).

**Comment by tamlyn10** [comment]
I agree with that @barnabee

**Comment by davidsiska-vega** [comment]
Current summary: to resolve we will have two types of "minimum stake" per asset; needs an update to assets specs, market lifecycle, lp-mechanics.  
1) Minimum stake to propose a market: large amount ~ 10000 USD to have "serious" markets proposed. 
2) Anti-spam minimum stake: small amount ~ 100-1000 USD.
