### ISSUE TITLE
Should these be network parameters: initial, search and release level?

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#381]
We haven't spec'd the following scaling parameters:
- search, initial, release.  

Clearly we need 1 < search < initial < release. 

In current implementation they are market parameters. I am thinking that these should perhaps be network parameters and I've just discussed with @tamlyn10 . 

@barnabee thoughts? 

And if we decide they are network parameters - which spec should we update to reflect this? At the moment they are "risk parameters for the market" in `0019-margin-calculator.md`.

**Comment by davidsiska-vega** [comment]
@barnabee , @tamlyn10  even if we keep them per market we need to update maybe the market framework or somewhere to put validation on the input. 

We found with Djordje today that you can have rather silly levels as an input.

**Comment by barnabee** [comment]
To me these collateral level scaling parameters make sense as a **risk parameter** because different models could call for different parameters so set these levels, and some may even set them automatically (trivially, for a 100% collateralised risk "model").

At the moment _all risk parameters sit in the market framework_, i.e. they are set on a per market basis and the specific parameters needed for a market are defined as part of the definition of the risk model/[margin calculator](https://github.com/vegaprotocol/product/blob/master/specs/0019-margin-calculator.md). Thus they are set in market proposals and through market goverance. 

But it would be possible to invent the concept of a **network risk parameter** which would _still be defined by each risk model/margin calculator_ (i.e. these scaling parameters would be specific to the model/calculator we're using) but _they'd be the same for all markets using that risk model/margin calculator_ and set via network parameter governance. We could even combine both types.

I am pretty ambivalent as to whether they should be market or network level, but reasonably certain they need to be specific to a risk model/margin calc. not global across all cases.

In either case, I think:

- [ ] We should update the [margin calculator spec](https://github.com/vegaprotocol/product/blob/master/specs/0019-margin-calculator.md#scaling-other-margin-levels) with the validation requirements
- [ ] We should at least expand the [_tradable instrument_ section in the Market Framework spec](https://github.com/vegaprotocol/product/blob/master/specs/0001-market-framework.md#tradable-instrument) to state that this means specifying a risk model and it's required risk parameters. (It may be that "risk model" in this spec should be margin calculator or even both, i.e. you need to pick a margin calculator and applicable risk model, although this is inconsequential while we only have one of each.)

If we want to make these network level, we'll also need to:

- [Change the margin calculator spec to describe them as network risk parameters
- Update the (still WIP?) network parameters spec to include the concept of network risk parameters

I'd suggest we keep them at market level for now to minimise the additional work we create (i.e. just spec updates and valdiation rather than changing parameter types too). Is there any reason it's worth considering changing to network level parameters now too?

**Comment by davidsiska-vega** [comment]
@barnabee Agree with both i.e.
i) for now(*) keep them at market level and update the validation for them in market framework (we can mention that they need to be in order in margin calc spec too) 
ii) in the future have them on the network level *per risk model*. 

@tamlyn10 you mentioned that you're working on updates to the "market framework", would you like to just include this?

**Comment by tamlyn10** [comment]
yeah,  my view is that the network has a role to play / is incentivised to make Vega a venue of quality markets, and the setting of these levels is critical to that - it influences how many close outs there are etc. I take the point about the full collateralisation type models, and so agree that these should be network parameters by risk model.

i'd prefer to switch to that now, so that during all the community education on market creation we don't have to add this into the dialogue (it will come up as we roll out more products, and at that point it's appropriate IMO).

any reason we wouldn't make that decision now?

note, the market risk parameters that define tau, sigma etc. would remain as mkt params for now.. these are what drive the maintenance margin amt.

**Comment by davidsiska-vega** [comment]
If we are switching to "network parameters per risk model" then I'd propose that we throw the \lambda parameter with them (this is the risk aversion). 

So, "network parameters per risk model for lognormal model":
- \lambda = risk aversion parameter = 0.0001, 
- release level scaling > initial level scaling > search level scaling > 1. 

And the remaining "per market risk parameters for lognormal model":
- sigma  = volatility = 200% = 2.0
- tau = maximum time step between risk events = 1 minute
- underlying growth mu = 0.00
- risk free rate r = 0.00

We can make the decision now and write the specs accordingly. The actual work will then get prioritised among all the other things that we want done.

**Comment by tamlyn10** [comment]
Yeah, I think that makes sense to me. I'd love to get this specced and sorted fairly soon as we kick off the community education around market creation, but shouldn't be a blocker to first public release..
