### ISSUE TITLE
Settling markets from held margin

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#392]
When proposing a market, we could enforce validation to protect the system in terms of risk/margins.

From risk point of view: the gap between "trading terminated" and "product expiry time" (defines within oracle data) should always be lower than \tau. Otherwise it's very likely that margin balances won't cover settlement.

`oracle-data-time - trading-termination-time >= tau`

**Comment by barnabee** [comment]
Bringing the essence of my comment from previous thread here:

- It is not possible to prove that this condition actually holds true at market creation, because we can't check the actual value of `oracle-data-time` until settlement itself, when the data is received (if we can check it at all!).
- By specifying a future with a termination time and a tau value we are already requiring that governance voters who do a good job validate that the data we take from the data source will be appropriate given the termination time and tau. We will definitely want to at least document this.
- There are definitely downsides/trade-offs to adding this that could limit market creators and allowable oracle sources, and the question is whether or not we gain enough for the complexity vs simple documenting the need to verify this to satisfaction during market governance, as for other parts of the proposal.

For instance, we could require (at the cost of less flexibility and extra complexity for market creators) all data sources used by futures to carry a timestamp field, then also make every market creator provide a mapping and filter conditions to that field. 
  - We'd then need to provide a way to check that the filter conditions would ensure the value of the field must meet the validation requirement for it to cause settlement, as we can't check the value of the field itself until actual settlement time,
  - We'd have to specify what formats were allowable, too, and would be unable to process data sources that format dates/times in a different way
- We'd be unable to process oracles where the identity of the source itself (i.e. a public key) defines it's parameters and it didn't contain a timestamp.
- Obviously it would be trvially easy for someone providing an oracle transaction in our MVP system to simply hardcode the value of the timestamp field to to be the one required by the source definition, and we'd have no way to prove it's correctness.

Happy to discuss further, but my initial thoughts are that it is probably not worthwhile to take the complexity hit to add this. All other validation such as whether the oracle represents the right price, whether tau is chosen correctly for the network, whether the other risk factors are reasonable given things like the historic volatility of the underlying, etc. all require significant external work and can't be validated by the protocol and my inclincation would be to say that this is one of those cases too.

**Comment by barnabee** [comment]
A suggestion though, would be that we make a community norm to include a filter on the timestamp field (e.g. as shown for the `mark_time` field in the below example JSON) of an oracle definition _if such a field is available and relevant_ that proves to the community that this condition is met, and that we'd reject a proposal if such a filter was possible for the oracle definition but not provided, even if it was not strictly required.

```javascript
    settlementPriceSource:  { 
        signedMessage: {
	    sourcePubkeys: ["YOUR_PUBKEY_HERE"],
	    field: "price",
	    dataType: "decimal",
	    filters: [ 
	        { "field": "feed_id", "equals": "BTCUSD/EOD" },
	        { "field": "mark_time", "equals": "31/12/20" }
	    ]
        }
    } 
```

**Comment by tamlyn10** [comment]
Barney, one thing I'm not clear on is how the expiry date-time is understood by traders if the filters field _is not available and relevant_? I understand everything you're saying above about validation. I'm raising this because as a trader I want to know the intent of the market expiry at a minimum.

**Comment by barnabee** [comment]
@tamlyn10 it's specified in the "future"product parameters (it's needed for the product to trigger `trading terminated`) so will be visible to anyone. But this doesn't give you any way to verify programmatically that the oracle actually meets the requirements of that expiry date, either for the tau provided or for the actual intent of the market based on its name and tags.

When people actually want to check the oracle and other aspects of the proposal they are definitely going to **need** to use data not available on chain to complete the verification and decide how to vote. Eventually this might happen via a block explorer (for instance, Etherscan — among others — does this for Ethereum, and lots of the info you see on there does not come from the blockchain). The forums will obviously also be a key source of info, as might websites of market creators, oracle providers etc. and even other blockchain services such as reputation protocols, etc.
