### ISSUE TITLE
Liquidity Provisioning Bots that don't burn cash all the time

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#442]
When [Liquidity Provisioning Orders exist](https://github.com/orgs/vegaprotocol/projects/50), [our current bots](https://github.com/vegaprotocol/traderbot) will no longer be up to the job. We need newer, fancier bots that use LP orders. Probably?

**NOTE** This is not a core spec. The work should not go in the specs folder.

**Comment by edd** [comment]
Idea: Let's make these in a new repo, open source from the start, so that other people can run them / contribute / build on them. I do not expect contributions day one, but a goal is that if someone else wants to provide liquidity, they can clone the repo

**Comment by davidsiska-vega** [comment]
I think current bots will be ok for now. We can set up markets as follows:
- One or more well funded bot or non-bot account (doesn't matter) commits to provide liquidity so that a market can launch. They peg all their liquidity to the mid price, far from the mid price.
- The current bots are unleashed on the market just like now - they will track a price source from elsewhere (providing realistic price) and place random orders (providing order book feel and trading activity).

**Comment by davidsiska-vega** [comment]
@edd I agree that *if* we want to develop any bare bones LP bots then let's do it in an open source repo.

**Comment by tamlyn10** [comment]
Discussion on Slack here: https://vegaprotocol.slack.com/archives/CLFN5CUMT/p1609861550227400

**Comment by tamlyn10** [comment]
Next step (as discussed in Research call 11/1):

@davidsiska-vega to produce a document that captures the requirements for Flamenco Tavern bots

**Comment by tamlyn10** [comment]
Draft PR ready to review. Meeting on Friday about it.

**Comment by davidsiska-vega** [comment]
This PR needs a little work after last meeting. Once it's merged this can be closed. https://github.com/vegaprotocol/product/pull/458

**Comment by tamlyn10** [comment]
@tamlyn10 @witgaw to review today and ideally we will try and merge tomorrow.
