### ISSUE TITLE
Evaluate when a Mainnet doesn't need to be reset

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#452]
Establish and document blockers

Note, this was a post WWN task from the Mainnet 2 spreadsheet.

**Comment by edd** [comment]
Semi related: https://github.com/vegaprotocol/VIPs/pull/1. While this task focuses on other people running validators, some of the pre-requisites are the same. In particular:

- We need validators joining the network after genesis (either because they crashed or because they're new) to be able to catch up. Currently executing a block is near enough real-time that they take too long to catch up, meaning we can't add validators back if they fall off on testnet
