### ISSUE TITLE
Extending withdrawals - e.g. Amt able to be specified as a %

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#456]
**Initial Idea:** Allow a withdrawal request to be specified in terms of percentage of the total amount of the asset that a participant has available at the point in time the tx is specified. 

**Context:**  On a call with Anton and Khaled from Flovtec, they expressed interest in the ability to submit a withdrawal request that would allow them to withdrwaw a percentage of their available balance. This avoids the problem of them submitting an absolute amount that could get rejected because the balance has changed since they submitted the TX. They noted Kraken as an example of this done well.

**Extension**
May be worth us thinking about other things like:
* Allow a withdrawal request across all assets (and including above percentage aspect).. so someone could request to withdraw 25% of all their available assets... (no idea if this is Ethereum / bridge possible?) 
* Allow conditional logic in a withdrawal.. like, "I'll withdraw up to whatever leaves me with a buffer of x % on my current margin allocation requirements"

**Comment by C0deMunk33** [comment]
So all of the calculation and everything for this would need to be on the Vega core side. The only thing I can add to help that's not going to be stupid is batch withdrawal, which is something I was considering.

Since the bridge only responds to orders from the validators, core can easily do the calculation. so the change here would be to find a way to say "withdraw 10 dai tokens AND 5 wbtc" which I can do. (understanding that the 10 dai and 5wbtc would have been calculated by core to be the 2% they want, doing this on ETH is prohibitive)

**Comment by C0deMunk33** [comment]
I had a discussion with @barnabee and he said that bulk withdrawals weren't necessary. I'll let you two deal with this.
