### ISSUE TITLE
LPs get easily wiped out by big bid-asks

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#530]
Currently probability of trading is calculated from mid price. 

If bid/ask is wide then volume pegged to best bid/ask can lead to outrageous volumes being required => LP needs a lot of margin or their stake gets rejected. 

Proposed solutions: 
1) Calculate probability of trading from peg rather than from mid. This will allow LPs to maintain markets with large bid-ask spreads. This may be undesirable *but* 
- if the bid-ask is too wide then no-one will trade at which point there is no fee income for LP. They have no income and capital locked - so why would they do it? 
- someone may come in and undercut their wide bid-ask ... resolving the problem. 

2) Implement probability-of-trading weighted margin for orders. This is relatively straightforward now that we have the probability of trading function. 

@barnabee / @tamlyn10 / @witgaw comments please.

**Comment by barnabee** [comment]
I think doing 1 perhaps makes sense regardless?

Thinking:

If I understand the proposal correctly we'd then effectively assume every price between best bid and best offer has `P(trading) = 1`, which seems reasonable because the true market price is not known (but must be between thouse bounds). 

Keeping in mind that one can peg to the mid which would mean that as an LP you're effectively expressing an opinion about how wide the max spread should be through your pegs, so that can be used to avoid _crazy_ spreads (I assume mid pegs would often be set a little wider than the usual spread on a market, but it makes sense to me that some LPs may use them to capture flow if the limit spread widens and address your first bullet point issue.

**Re: proposal 2**, I think yes to this at some point too, although we should consider whether we want some uplift on the "raw" probability weighted margin or whether there should be a minimum probability applied to an order?

**Comment by davidsiska-vega** [comment]
@barnabee cool, yes I think we can do *Option 1* as it makes sense. Indeed your explanation of this is good between bid and ask we set `P(order will trade) = 1` for the purposes of weighting. I'll do some spec updates and PR... 

Regarding *Option 2* I agree we should push that to "at some point". I also like the idea of having a floor on probability of trading for setting the cost of margin. This will have the benefit of, if nothing else, acting as spam protection (you cannot dump arbitrary volume in the wings for free).

**Comment by barnabee** [comment]
Awesome, thanks David and agree re: both making option 2 an "at some point" change and also the point about spam.
