### ISSUE TITLE
Coded features review: on-chain rewards

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#564]
I suspect this should be updated to point to this spec: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0057-reward-functions.md#staking-and-delegation-required-for-

A lot of the work on the on chain rewards system is being sidestepped for [Sweetwater](https://github.com/vegaprotocol/specs-internal/blob/master/milestones/2.5-Sweetwater.md) - rather than testing 'on chain rewards' in total, we should verify that the one reward required for Sweetwater works as expected. The reward is outlined in the spec I put at the top. That reward is calculated as per https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md

There are some other relevant specs:
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0056-rewards-overview.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0055-on-chain-treasury.md

**Comment by edd** [comment]
I suspect this should be updated to point to this spec: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0057-reward-functions.md#staking-and-delegation-required-for-


There are some other relevant specs:
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0056-rewards-overview.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0055-on-chain-treasury.md

However as they hopefully make clear, a lot of the work is being sidestepped for [Sweetwater](https://github.com/vegaprotocol/specs-internal/blob/master/milestones/2.5-Sweetwater.md) - rather than testing 'on chain rewards' in total, we should verify that the one reward required for Sweetwater works as expected. The reward is outlined in the spec I put at the top. That reward is calculated as per https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md

**Comment by davidsiska-vega** [comment]
Btw @eyongegbe see also https://github.com/vegaprotocol/specs-internal/issues/630 as some changes to details of calculations can come from there.

**Comment by gordsport** [comment]
superseded by https://github.com/vegaprotocol/specs-internal/issues/563
