### ISSUE TITLE
Spec clarification - limited network life

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#591]
One of our community was asking whether we would be carrying over markets / marketIDs after resets. After a discussion with @davidsiska-vega we decided to raise this as an issue to discuss whether to edit the spec to make the following more clear.

Alpha/ Oregon Trail implementation, markets have the following status' [see market lifecycle spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0043-market-lifecycle.md):
1. Proposed
2. Rejected
3. Pending (opening auction)
4. Active
5. Suspended
6. Trading Terminated
7. Settled

Spec currently only says we want to carry over market proposals but contradictorily it also says: _Governence proposals that haven't been enacted yet aren't stored._

It also appears that Vega token holders ideally won't accept market proposals that expect to settle after `markets_freeze_date ` which will always precede the `chain_end_of_life_date`. Therefore, all open markets are meant to have settled and none should exist in any status after  `pending`.

Question:
* Is my understanding of that no marketIDs will be carried over because assumption is that all markets will have settled already?
* By implication am I correct in assuming the markets that the community will be encouraged to create will be shorter expiry than the expected reset times (e.g. weekly markets)?
* Do we want to carry over proposed markets? If so, this is an exception to the governance proposals not carrying over . Do we restore the history of the voting on these proposed markets?

Spec clarification tasks:
- [ ] Add `markets_freeze_date` to governance spec. (A governance proposal to change markets_freeze_date and chain_end_of_life_date must check that chain_end_of_life_date > markets_freeze_date.)
- [ ] Edits for clarification based on questions above
- [ ] Add network parameters to spreadsheet / new spec file

**Comment by barnabee** [comment]
> Governence proposals that haven't been enacted yet aren't stored.
Can you point me to the line that says this @edd or @davidsiska-vega. I can't find it but I am not 100% sure I'm looking in the right branch.

My expectation is that market creation/update proposals that are accepted (voting period has ended and the proposal passed the vote) will be stored. I think there are scenarios that test this, including the logic to shift the enactment time if is is before or too close to the time the network is started again.

If that is correct then I'd expect the market to have the same ID before and after restore.

It's also important to consider what happens if the network is unexpectedly restarted prior to the planned end of life. If markets are recreated in this case, I would also expect IDs to match pre- and post-reset.

(Original message restored by Edd)

**Comment by edd** [comment]
> Governence proposals that haven't been enacted yet aren't stored.
> Can you point me to the line that says this @edd or @davidsiska-vega. I can't find it but I am not 100% sure I'm looking in the right branch.
[snip]
> If that is correct then I'd expect the market to have the same ID before and after restore.
- A market ID matches a proposal ID, so this should work: https://github.com/vegaprotocol/vega/blob/f7a69ee3709609a7d4ebd71a8451dd04ae827745/governance/engine.go#L34
- The spec has been updated to say that all proposals will be stored, so that part of the question is no longer relevant

**Comment by edd** [comment]
So the only remaining question is:

> By implication am I correct in assuming the markets that the community will be encouraged to create will be shorter expiry than the expected reset times (e.g. weekly markets)?

@barnabee  the answer to this is ‘Yes’, right? i.e. it’s up to governance to ensure that markets are correct rather than any new code? If so I think we can close this issue as @tamlyn’s concerns are handled in the merged spec.

**Comment by barnabee** [comment]
Yeah that's correct. This is something governance needs to check. Also see my final comment above:

> It's also important to consider what happens if the network is unexpectedly restarted prior to the planned end of life. If markets are recreated in this case, I would also expect IDs to match pre- and post-reset.

Whatever we do here would apply if a market does settle on time, either because it was configured too long dated or an oracle failed. I think what we do here is to not restore the market, and to credit parties' last recorded margin balances to their general accounts.

**Comment by edd** [comment]
@barnabee alright - if you can add that to https://github.com/vegaprotocol/specs-internal/blob/master/non-protocol-specs/0003-limited-network-life.md#restoring-a-checkpoint then we can close this issue

**Comment by davidsiska-vega** [comment]
Limited network life spec has been updated since this was discussed and seems consistent now. Closing.
