### ISSUE TITLE
Limited network life: future areas to consider

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#621]
This is not a mainnet-proper problem as we won't be rebooting frequently, but:
- Right now if we intentionally shut down the network, and a validator unstakes on Ethereum between resets, and then the network starts up, that isn't a problem because the validator set is fixed and unchanging and there are no own stake requirements
- In the distant future when we don't reset the network ever again, this is fine as the proper mechanisms will be in place to change validator sets

However between those two points, there are some points that aren't well covered at the intersection of the Limited Network Life & Staking specs
- If we do implement minOwnStake (see research paper) to require that a validator has its own stake, and that validator is expected at Genesis and has no stake, what happens?
- If the network shuts down, and before the network starts up again one of the validators disappears from the internet, what is the process for starting up?
- If the network shuts down and 50% of the validators decide to try to start up different networks from the same checkpoint, what problems does that present? Presumably they can't allow withdrawals from the asset pool (as they wouldn't have sufficient control of the multisig contract to sign a bundle), but that could prevent anyone from withdrawing from the pool? I guess the network would also not start up.

Note: These are mostly @peterbarrow's, I'm just filing the issue.

**Comment by Vegaklaus** [comment]
The issue with minOwnStake can only happen if a validator unlocked (some of) their
tokens while the network was gone. There will be a mechanism anyway through which
all validators - before genesis - need to go through the Ethereum chain to see
if anything changed that affects their weights, so the other validators should
be aware of this and thus be able to eliminate the offending validator before
genesis even starts.

- We may want to change the auto-delegate after unlock function so that the 
the auto-undelegate linked to a validator does not auto-undelegate their own stake.
- The issue that still can occur here is that the validators are not synchronised on
what the last block of the Ethereum chain is, so if the unlocking was timed well, 
there may be a disagreement on the validator set. This is solvable, though I need
to think a bit on what the best way to do that is.
- If this happens on a large scale (e.g., half the validators being knocked out this way), 
then there's a problem. If that happens there's a big issue anyway, though. If we loose
more than a third of the validators at once, for example, we lose control over the 
smart contract.


One validator disappearing would not be an issue, as (with 13 validators) we can tolerate
the absence of 4 of them (which should also apply to the startup process, though I 
need to verify that). In this, there shouldn't be a very big difference between this
happening while the network is down or during normal operation.

If more than one third of the validators disappear/do their own thing, the network is
dead. There's slightly different thresholds for the smart contract (one validator, one vote)
and the consensus, but 50% of all validators going should shut it all down.
For the consensus, this could be rescued in theory (the delegators to bad validators can unlock 
their tokens, which will change the weights on the startup process so that the rest could
restart without violating the protocol. The smart contract is another issue though - at 
this point, we have no community-recovery mechanism to this end.

One thing we could do, for example, is to give all stakeholders over 0.1% of tokens key shares
for a emergency backup key that can change the multisig, though that's another topic
and should be discussed with legal.

**Comment by davidsiska-vega** [comment]
Solution in these extreme cases will probably have to be manual. 

We also don't expect LNL to be used anymore now we have protocol upgrade spec https://github.com/vegaprotocol/specs/blob/master/protocol/0075-PLUP_protocol_upgrades.md
