### ISSUE TITLE
Rewarding / punishing validator performance / lack of 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#654]
At the moment if a party is in the validator set it is treated as a validator for the purposes of simple POS rewards. This means that they are eligible for rewards (and those who delegate to them likewise) whether they are participating in running the protocol, producing blocks ...  or not. 

Soon after 💧 Sweetwater we want ways to avoid blatant freeloading.

**Comment by davidsiska-vega** [comment]
Discussed in research hour:
- use ping to see if people are down
- use being a leader: if you're missing your leader slots, you're not a leader in a period of time then you get penalised
- social aspect: make visible some statistics about how each validator is contributing to each block
- @Vegaklaus to create a roadmap

**Comment by Vegaklaus** [comment]
Full performance is hard (as we don't want to punish validators that are slower than the top 2/3 due to geography and (somewhat) due to added security), and Tendermint doesn't give us the information on who signed but was too late for their signature to make it into a block. We can detect someone who is offline for more than a few blocks though by them failing in their role as a leader (This causes them to miss proposing a block, and then other validators waiting for a timeout, so it's double bad).  So a quick solution would be

rewardScaling = <number of times acted as a leader>/<number of times you should have done so>

(with the reward they don't get going into the treasury - we don't want to motivate validators to make other validators look bad).

A more complicated add-on would be to also decrease the weight of offline validators, e.g., if you miss being a leader 100 times in a row, your weight is decreased by 1% (as is your reward). Assuming a blockspeed of 1s, that would be 20 minutes offline to lose 1% weight (which then can be restored at the same pace if you're up again).

**Comment by davidsiska-vega** [comment]
Validators also need to run ethereum event forwarder to be "useful". How do we ascertain this and how do we include this in the above?
