### ISSUE TITLE
Floating point non-determinism

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#689]
Investigate potential for consensus layer conflicts due to numerical discrepancies coming from floating point non-determinism (and ways of mitigating these).

Investigate:
- [ ] Probability of trading (check resulting LP order volumes)
- [ ] Risk factors

Strategies:
- Run same calculation (perhaps with a range of input values) on multiple threads on one machine (better yet one architecture type on different machines) and check if the results always agree, if not, check how should these be truncated. This will allow us to have reasonable confidence that requiring all validators to use same architecture will allow us to circumvent the problem.

Notes:
- Can use `max(p,min)/min` where `p` is the probability of trading coming from the risk model and `min` is the minimum probability of trading network parameter. That way we get something that's always geq 1, can floor to int (so that the min is the least multiple of prob. of trading we're dealing with) and then transform back to a fraction.

**Comment by davidsiska-vega** [comment]
Discussion in research offsite:
- send things through consensus
- what gets sent should be map: a hash of inputs to outputs 
- there have to be sensible defaults for the values so that the core has something to use before the first calculated values come through 
- after this has been sent outputs get averaged (correctly) using e.g. median 
- each gets a slot per market in which the more recent submission is stored and used for the averaging above. 
- submitters should submit either periodically e.g. once a minute OR triggered by market state (more than 10% mark price move)
- each submission needs an identifier tied to a point in time or a sequential serial number so we're sure the bucket has the most recent
- consider spam protection aspect of this but not as part of this spec.

Create a spec which covers this; say what we want, not how in the spec.

**Comment by witgaw** [comment]
Spec now merged https://github.com/vegaprotocol/specs-internal/pull/761
