### ISSUE TITLE
Update 0059-simple-staking-and-delegating.md to include the 💦 feature of 'Auto distribute newly associated tokens'

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#697]
In order to start development on the 💦 feature of 'Auto distribute newly associated tokens' we need the 0059-simple-staking-and-delegating.md updated to include information for the team to review and start development:

- [ ] Spec updated to detail the feature for development
- [ ] Acceptance criteria so that the feature can be tested (@vega-paul)
- [ ] Detail any QA scenarios for feature files (if applicable @cpuja84)

**Comment by davidsiska-vega** [comment]
The idea here is imagine a party P has 1000 VEGA associated with the network and the following current delegation choices:
- validator A 80% i.e. 800 VEGA
- validator B 10% i.e. 100 VEGA
- validator C  5% i.e. 50 VEGA
- currently undelegated 5% i.e. 50 VEGA.  

Party P now associates another 100 VEGA in the network. What now happens is:
- party P now has additional 80 VEGA delegated validator A so 880 VEGA unless (*)
- party P now has additional 10 VEGA delegated validator B so 110 VEGA unless (*)
- party P now has additional 5 VEGA delegated validator C so 55 VEGA unless (*)
- party P has additional 5 VEGA undelegated i.e. 55 VEGA unless (*) 

(*) if the maximum tokens per validators are reached then this amount goes to the undelegated bucket. 

Party P now *un*associates 200 VEGA tokens the delegation is again reduced proportionally. What happens is:
- party P now has 160 VEGA fewer delegated validator A so 720 VEGA 
- party P now has 20 VEGA fewer delegated validator B so 90 VEGA 
- party P now has 10 VEGA fewer delegated validator C so 45 VEGA

**Comment by ze97286** [comment]
@davidsiska-vega @Vegaklaus A few questions/comments on this:

1. The undelegation part  is already done proportionally - in the case of stake dissociation

2. Should there be a flag somewhere in the staking bridge or elsewhere indicating that the party wants to have their stake auto-delegated?

3. When does the auto delegation kicks in? only if the party had all of their stake delegated at the beginning of the epoch and then increased their stake during the epoch? Looking at a couple of cases - case1, party1 has associated 1000 VEGA and delegated a 100 to node1. I would imagine we do not auto-delegate anything in this case until they have delegated the whole 1000 tokens. Case 2: party1 has 1000 VEGA associated and distributed them between nodes 1, 2, 3. During the epoch they associate 500 more tokens - at the end of the epoch we delegate the 500 tokens proportionally between nodes 1, 2, 3. Does that make sense? 

4. In case during the epoch - the party requests to manually delegate/undelegate from a node, no auto delegation takes place. Auto undelegation always takes place in cased of dissociation because this is applied to the running epoch so they don't get rewarded for dissociating stake during an epoch. Is that correct? and also, what should happen on the next epoch - suppose they did nothing for the next epoch, now at its end they have un-nominated stake - do we auto distribute it? or do we only trigger auto-delegation when the balance of the staking account increases? 

5. What should happen if during the epoch the party requests to undelegate NOW - if they haven't dissociated tokens they now have free undelegated tokens - do we auto delegate them or not? I would think not, but what should be the rule here? 

6. It's not clear to me what is meant by the comment "if the maximum tokens per validators are reached then this amount goes to the undelegated bucket." - suppose in the example above we want to add 80 to validator A based on the proportion but due to max per validator cap we can only add 10 - do we add the 10? how do we distribute the rest based on the proportion? i.e. 10 and 5 to validators B and C? or do we delegate more because we can?

**Comment by davidsiska-vega** [comment]
1. Cool.

**Comment by davidsiska-vega** [comment]
2. Yes, that would be ideal but it would delay getting the bridge audited.

**Comment by davidsiska-vega** [comment]
3.  
case1: I would still auto delegate proportionally as the example above describes but I agree that not auto-delegating if the whole allocation hasn't been used is also sensible. 

case2: yes, that makes sense (there will be some rounding decisions but anything that adds up makes sense)

**Comment by davidsiska-vega** [comment]
4. 

> In case during the epoch - the party requests to manually delegate/undelegate from a node, no auto delegation takes place. 

I agree with this. 

> Auto undelegation always takes place in cased of dissociation because this is applied to the running epoch so they don't get rewarded for dissociating stake during an epoch. Is that correct? 

I believe that's correct but I haven't checked the implementation or the intention @Vegaklaus, what does the spec say?

> and also, what should happen on the next epoch - suppose they did nothing for the next epoch, now at its end they have un-nominated stake - do we auto distribute it? or do we only trigger auto-delegation when the balance of the staking account increases?

I got a bit lost here. We only want to use "auto-delegation" when stake is associated / dissociated (so Ethereum staking bridge event). You already said in 1. that "dissociation" of Vega tokens is covered. So in that sense we only want to change the behaviour when the amount of associated tokens increases. We don't want to do it when they manually undelegate from say node A. But maybe that's not helpful in light of what you said.

**Comment by davidsiska-vega** [comment]
5. undelegate should never lead to automatic distribution. So the party should end up with some undelegated tokens associated to Vega.

**Comment by davidsiska-vega** [comment]
6. my simple solution was that if I cannot add the whole 80 then they simply go into the bucket of tokens that have no delegation. 

Your suggestion, that if 10 could be delegated then we delegate 10 and only have 70 to deal with now would also work for me. 

The decision is now to be made: do they go in the "undelegated" bucket? Or do we try to delegate proportionally to B and C? I think trying that is valid (but more complicated so I won't bother, I don't like complication).

**Comment by ze97286** [comment]
> I got a bit lost here. We only want to use "auto-delegation" when stake is associated / dissociated (so Ethereum staking bridge event). You already said in 1. that "dissociation" of Vega tokens is covered. So in that sense we only want to change the behaviour when the amount of associated tokens increases. We don't want to do it when they manually undelegate from say node A. But maybe that's not helpful in light of what you said.

What I'm asking is this - suppose the party requested to undelegate 100 tokens from node1, we do that at the end of the the epoch and we don't redistribute anything. However at the end of the next epoch - we're looking at this party and they have 100 undelegated but associated tokens. I guess what this comes down to is if auto-delegation is done *only* in cases of increase/decrease of *association* or also upon tokens becoming available for redistribution through undelegation - even if an epoch later - to give the party an opportunity to decide for themselves

**Comment by edd** [comment]
>     1. Yes, that would be ideal but it would delay getting the bridge audited.

Given the contract audit is already in a queue to get started soon, now is not the time to make a change to the contract. We have two choices, as I see it:

1. Do it without a contract change
2. Don't do it now

Currently, it's option 1.

**Comment by davidsiska-vega** [comment]
Thanks @ze97286 . Now I understand. I believe that the behaviour I had in mind is 

> auto-delegation is done only in cases of increase/decrease of association 

but with epochs potentially long e.g. 24h it means that as a user I need to take 2 actions: 1 undelegate in this epoch and assign delegations in next epoch. 

But it's blockchain, they can write a little script to do it for them if it bothers them. So I'd still stick with 

> auto-delegation is done only in cases of increase/decrease of association

**Comment by ze97286** [comment]
ok, here's a summary for my proposal based on the above discussion. The most important point to note here is (7) which makes sense to me but I could be convinced otherwise. I'm using delegation/nomination interchangeably. 
@davidsiska-vega @Vegaklaus @gordsport 
--------

1. Auto un-delegation - once the association balance of a party during an epoch has gone below the balance at the beginning of the epoch - their delegation stake is adjusted accordingly - i.e. if they had total nominated balance > minimum associated balance during the epoch - their nomination balance is adjusted such that their balance for the epoch is capped at the minimum balance they had associated during the epoch - this must be done such that the party is not rewarded for any stake dissociated during the epoch even if they cover for it in associating. The undelegation is proportional to the nomination balances at each validator. There's some subtlety here - suppose the party had a 100% of their stake associated at the beginning of the epoch, on the first block they dissociate and on the last block re-associate. They should be rewarded for nothing, which is the case, but they would have the whole associated stake un-delegated, but at the end of the epoch they have their whole stake ready to be delegated again - the case of a 100% undelegation is less interesting however than smaller amounts but the point I take from this which is later discussed again in (7) is that any undelegation (automated or manual) takes us off auto-delegation mode for the party until it qualifies again (through manually delegating their associated balance). Auto undelegation is currently implemented and supported as specified above. 

2. Once a party has reached over x% of their associated vega tokens nominated they become eligible for auto delegation - the reason this is x% rather than 100 is that due to rounding issue they may never have 100% delegated. 

3. Auto delegation means that at the end of each epoch, as long as the party has unnominated balance - it will be attempted to be distributed proportionally to their nominated validators - as long as no manual delegations are attempted during the same epoch. 

4. The reason this is not a one off is that there may be unlucky timing such that not all of the balance can be distributed in one epoch due to max per validator limitations.
 
5. If there is no space left on the validator to which auto delegation is attempted, the balance will be left undelegated and will be retried in the next epoch if it qualifies according to (1)

6. The potential stake to be auto-delegated is counted for max delegation per validator - otherwise there is unlikely to ever be much space available for auto-delegation 

7. NB: any undelegation request done while there's an un-nominated but associated balance - gets us off auto delegation mode until the next time (2) applies. The rationale is to give the party a change to redistribute their nomination. 

**Normal scenario auto undelegation:**
1. epoch 0: party associated 1000 VEGA 
2. epoch 0: party nominated 200 VEGA to validators 1-5
3. epoch 1: party dissociated 200 VEGA
4. at the end of epoch1: party one would have left 160 tokens nominated to validators 1-5 (for both epoch 1 and onwards - the former is important so that they don't get rewarded for 200 per validator)

* this is already implemented and tested. 

**Normal scenario auto delegation:**
1. epoch 0: party associated 1000 VEGA 
2. epoch 0: party nominated 200 VEGA to validators 1-5
3. epoch 1: party associated 200 VEGA
4. end of epoch 1: there's sufficient space on each validator 1-5 to accept the delegation of 40 VEGA from party 1 and party1 now has delegation of 240 for validators 1-5 for epoch 2.

**Edge case 1: manual delegation for party eligible for auto delegation:**
1. epoch 0: party associated 1000 VEGA 
2. epoch 0: party nominated 200 VEGA to validators 1-5
3. epoch 1: party associated 200 VEGA
4. epoch 1: party requests to delegate 100 VEGA to validator1
5. end of epoch1: party1 has 300 delegated to validator1, 200 delegated to validators 2-5 and 100 remain undelegated. 
6. end of epoch2: the remaining associated undelegated 100 VEGA get auto-delegated and distrubuted such that validator1 gets 27 (100 * 300/1100) and validators 2-5 get each 18 - and 1 token remains undelegated

**Edge case 2: manual undelegation for party eligible for auto delegation:**
1. epoch 0: party associated 1000 VEGA 
2. epoch 0: party nominated 200 VEGA to validators 1-5
3. epoch 1: party associated 200 VEGA
4. epoch 1: party requests to undelegate 100 VEGA from validator1
5. end of epoch1: party has 300 unnominated VEGA which will NOT be auto delegated 
6. epoch 2: party requests to delegate 300 to validator 2
7. epoch 2: party associated 100 VEGA 
8. end of epoch 2: party has 500 nominated to validator2 and 200 nominated to validators 3-5
9. end of epoch 3: party has 100 unnominated VEGA which gets nominated proportionally between validators 2-5

**Edge case 3: respecting max per validator** 
1. epoch 0: party associated 1500 VEGA 
2. epoch 0: party nominated 100, 200, 300, 400, 500 VEGA to validators 1-5 respectively
3. epoch 1: party associated 300 VEGA
4. end of epoch 1: according to the proportion of nomination, validators need to get 20,40,60,80,100 respectively - however max per validator implies availale balances of 100, 80, 60, 40, 20 for validators 1,2,3,4,5 respectively
   meaning that at the following delegation will apply: 120, 240, 360, 440, 520. There will be no attempt to top up validators against the proportion implied by the nomination.

**Comment by davidsiska-vega** [comment]
@ze97286 that sounds all very sensible to me.

**Comment by ze97286** [comment]
perfect

**Comment by gordsport** [comment]
@davidsiska-vega @Vegaklaus - can the spec 0059-simple-staking-and-delegating.md be updated now to reflect the above proposal?

**Comment by Vegaklaus** [comment]
> 
> > Auto undelegation always takes place in cased of dissociation because this is applied to the running epoch so they don't get rewarded for dissociating stake during an epoch. Is that correct?
> 
> I believe that's correct but I haven't checked the implementation or the intention @Vegaklaus, what does the spec say?
> 
It's both intent and spec; the spec (0050) says that we trigger undelegate_now, which 0059 says forfeits the rewards for that epoch.

**Comment by Vegaklaus** [comment]
There's one scenario here where this can go wrong (unless a user can turn this feature off); I might undelegate in epoch x with the intend to sell my tokens, then needing more than an epoch for the sale, which means my tokens are auto-delegated and then auto-undelegated once the sale goes through, which leave me with a different distribution than the one I intended. We could settle this by auto_undelegate first undoing the last auto_delegate to see if that frees enough tokens, or is that too complicated ?

**Comment by ze97286** [comment]
@Vegaklaus the scenario you're describing won't happen because once the party has undelegated, they're effectively turning off auto delegation until they qualify again for auto delegation via delegating (manually) over x% of their associated stake.

**Comment by Vegaklaus** [comment]
Ok, missed than, thanks.

**Comment by cpuja84** [comment]
> Edge case 2: manual undelegation for party eligible for auto delegation:
> epoch 0: party associated 1000 VEGA
> epoch 0: party nominated 200 VEGA to validators 1-5
> epoch 1: party associated 200 VEGA
> epoch 1: party requests to undelegate 100 VEGA from validator1
> end of epoch1: party has 300 unnominated VEGA which will NOT be auto delegated
> epoch 2: party requests to delegate 300 to validator 2
> epoch 2: party associated 100 VEGA
> end of epoch 2: party has 500 nominated to validator2 and 200 nominated to validators 3-5
> end of epoch 3: party has 100 unnominated VEGA which gets nominated proportionally between validators 2-5

@ze97286 - Why at the end of epoch 3 when auto delegation gets triggered, validator 1 is excluded ? Is it because party undelegated from it in the epoch 1 ? I didn't read about any specific rules for exclusion of a particular validator (due to undelegation) so far for autodelegation. Am I missing something here ?

**Comment by cpuja84** [comment]
> Auto delegation means that at the end of each epoch, as long as the party has unnominated balance - it will be attempted to be distributed proportionally to their nominated validators - as long as no manual delegations are attempted during the same epoch.

@ze97286 - Not to be picky but in absence of a spec, just trying to understand the feature. In the above you actually meant `manual delegations / undelegation` during an epoch. We aren't distinguishing between delegation or undelegation actions as such to invoke Auto delegation. Correct ?

**Comment by ze97286** [comment]
@cpuja84 

> @ze97286 - Not to be picky but in absence of a spec, just trying to understand the feature. In the above you actually meant manual delegations / undelegation during an epoch. We aren't distinguishing between delegation or undelegation actions as such to invoke Auto delegation. Correct ?

Undelegation actually gets us out of auto delegation mode. If a party qualifies for auto delegation AND they have available stake BUT had manual delegations - we don't apply auto delegations at the end of *this* epoch. If on the next epoch they still have available stake - auto delegation will take place. If the party qualifies for auto delegation AND they have available stake BUT requested undelegation (either now or at the end of the epoch) - they are disqualified from auto-delegation and their stake remains untouched until they delegated it themselves.

**Comment by ze97286** [comment]
@cpuja84 

> @ze97286 - Why at the end of epoch 3 when auto delegation gets triggered, validator 1 is excluded ? Is it because party undelegated from it in the epoch 1 ? I didn't read about any specific rules for exclusion of a particular validator (due to undelegation) so far for autodelegation. Am I missing something here ?


You're not missing anything. I didn't set the numbers right. It should be:
Edge case 2: manual undelegation for party eligible for auto delegation:
epoch 0: party associated 1000 VEGA
epoch 0: party nominated 200 VEGA to validators 1-5
epoch 1: party associated 100 VEGA
epoch 1: party requests to undelegate 200 VEGA from validator1
end of epoch1: party has 300 unnominated VEGA which will NOT be auto delegated
epoch 2: party requests to delegate 300 to validator 2
epoch 2: party associated 100 VEGA
end of epoch 2: party has 500 nominated to validator2 and 200 nominated to validators 3-5
end of epoch 3: party has 100 unnominated VEGA which gets nominated proportionally between validators 2-5 - i.e. validator 2 gets 45, validator 3-4-5 get 18 each

**Comment by cpuja84** [comment]
> Undelegation actually gets us out of auto delegation mode. If a party qualifies for auto delegation AND they have available stake BUT had manual delegations - we don't apply auto delegations at the end of this epoch. If on the next epoch they still have available stake - auto delegation will take place. If the party qualifies for auto delegation AND they have available stake BUT requested undelegation (either now or at the end of the epoch) - they are disqualified from auto-delegation and their stake remains untouched until they delegated it themselves.

@ze97286 - Yes makes sense. So if within an epoch which is eligible for auto delegation as soon as a manual delegation or undelegation is trigged, auto delegation is turned off (or gets disabled ) for that epoch.

**Comment by ze97286** [comment]
> @ze97286 - Yes makes sense. So if within an epoch which is eligible for auto delegation as soon as a manual delegation or undelegation is trigged, auto delegation is turned off (or gets disabled ) for that epoch.

Undelegation turns it off completely not just for the epoch - until it qualifies again for auto delegation meaning the party has manually delegated all of their stake. For delegation, yes correct. The rationale for that is that if they undelegate they may want to reorganise their delegation so auto delegation will just get in their way.

**Comment by cpuja84** [comment]
> > @ze97286 - Yes makes sense. So if within an epoch which is eligible for auto delegation as soon as a manual delegation or undelegation is trigged, auto delegation is turned off (or gets disabled ) for that epoch.
> 
> Undelegation turns it off completely not just for the epoch - until it qualifies again for auto delegation meaning the party has manually delegated all of their stake. For delegation, yes correct. The rationale for that is that if they undelegate they may want to reorganise their delegation so auto delegation will just get in their way.

Ahaa okies !! And for the rule for qualification again (post undelegation) is increase / decrease of staking balance ?

**Comment by ze97286** [comment]
to qualify again they need to have x% of their stake delegated manually. Then when they have more stake it will be auto delegated.

**Comment by gordsport** [comment]
Spec updated in line with the conversation above
