### ISSUE TITLE
Current way staking is done is hard to reason about

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#740]
Current way staking is done is hard to reason about and leads to sub-optimal user experience.  

1) Someone who tries to delegate doesn't know how much stake they ended up putting onto a node until the end of epoch (24h is a long time to wait). Potentially, to delegate the whole associated stake, an unlucky user might have to attempt an unlimited number of days in a row. 

2) We have no way of communicating this in the UI. This is mainly not lack of APIs but the whole design that tries to reconcile staking and un-staking requests only at the end of an epoch. 

A suggested change of approach: process the delegation / un-delegation transactions immediately and on first-come first-served basis (like we do with orders). So we will not be reconciling delegation amounts at epoch start. 

During epoch `n` everything is fixed for calculating rewards at the end of epoch end. If people add stake or remove(*) stake during epoch it won't affect their rewards. 

People can submit staking requests for period `n+1` during epoch `n`. We process those requests to add / remove stake to validators immediately in the order they come in. At the end of period `n` we pay the rewards for `n` as per the amounts fixed at start of `n`. At start of period `n+1` we freeze the end stake of staking and delegation requests that were processed during `n`. These will then determine rewards at the end of `n+1` . And so on. 

(*) There should be an "nuclear" unstake option which will remove stake from a validator if the user has a reason to think the validator is cheating. If this happens remove the stake from the validator during `n` for the purposes of consensus weight (which by the way we don't have implemented) but let whoever delegated still get their rewards. They cannot get any more rewards for this epoch even if the put the removed stake on another validator they can only get rewarded for `n+1`.

**Comment by Vegaklaus** [comment]
The problem is that there is information we only have at the end of the Epoch that determines if staking succeeds or fails. If we process right away, the first person to ever stake will thus result in one validator having 100% of all stake, thus too much, thus will fail, and so on. This is mainly a startup problem (so we could fix it by setting minVal to 1 in the beginning and thus effectively deactivating the anti-whaling), but the issue will stay that we will always reject transactions this way that in the current scheme go through.

**Comment by davidsiska-vega** [comment]
If I have 100% of the associated stake (which is what enters the max calculation) and I try to delegate all to one node it will fail. Agreed. 

But the Core can immediately respond with a very informative error message / rejection reason. It can tell me that max delegatable to one node was a given amount. I can then delegate uniformly across the nodes if I wish to having this bit of info.

Or, if I don't want to be uniform I wait for others to associate & delegate and then I repeat. 

But one way or another, if it fails we can make it immediately clear why it failed.

**Comment by davidsiska-vega** [comment]
@Vegaklaus since we have the current behaviour implemented we could also use that during epoch `0` but then switch to the `first come first serve` method in the subsequent ones.

**Comment by Vegaklaus** [comment]
Epoch 0 may be to short, Epoch_{Coinlist_Stakes} might be better

**Comment by Vegaklaus** [comment]
Or, we define a reasonable percentage of stake we assume will be staked once everyone found their ledger, and turn it on once that percentage is reached

**Comment by davidsiska-vega** [comment]
@Vegaklaus could we also have the following:

The `total_delegated` (which really is total associated to Vega chain) can be replaced by `max(total_delegated, min_expected_associated_amount)` 
and the `min_expected_associated_amount` is to be a network parameter to be set to 30 million VEGA. 

This way we help the bootstrap phase while everyone is figuring out how their storage provider can interact with the Ethereum staking contract. 


 

https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0061-simple-POS-rewards%20-%20SweetWater.md

**Comment by Vegaklaus** [comment]
That should do to, we'd just need to check the code to see if some results involving that_delgated are refused somewhere else (it should not impact the reward distribution, but better be sure). The difference is that this would still set some limit, while minVal=1 turns of anti whaling altogether (which shouldn't make any practical difference).

One question to discuss still, if the amount of staked tokens drops below the threshold, do we move back too bootstrapping mode (my initial instinct was not to for no solid reason, this approach would do it)

**Comment by witgaw** [comment]
What about this anti-spam thing that requires the tokens to be associated for one epoch before delegation can be done (if I'm even describing it correctly). 

I find that really confusing, and don't like the fact that delegation (any, let alone "full use of associated tokens" delegation) cannot be achieved in "one sitting".

**Comment by davidsiska-vega** [comment]
@witgaw, that issue (antispam / association epoch) is already take care of thanks to @ze97286 , we just need to edit the spec to match reality ;-).

**Comment by barnabee** [comment]
I wnoder if a better solution might be not to reject staking that takes a node above the threshold but just to penalise all the stakers to that node with lower per-stake rewards so that they have an incentive to move some of it.

That way nomination to a valid validator would be guaranteed to succeed immediately (it just wouldn't take effect until next epoch) and you could have a real time view of your current expcted rewards "efficiency" vs the max possible all the way from the time you staked up to the start of the epoch.

Would there be any downsides to this?

**Comment by Vegaklaus** [comment]
This was a problem for the Validators that have a contract with the exchanges; it may mean that if they get popular for some reason), they can't offer their customers the same return of investment as other validators; the exchanges, working only with Validators they have contracts with, would then offer those worse conditions to all their customers, and everyone suffers a dent in reputation.

**Comment by davidsiska-vega** [comment]
So there is already the penalty whereby the validator score doesn't grow once the max is exceeded (remember it's possible to be over the max if e.g. someone delegates, then dissociation happens and hence max changes). 

This currently is:
```
  s_minVal = 5 // as an example
  s_numVal = numberOfValidators   
  a = Math.max(s_minVal, s_numVal/s_compLevel)
  linearScore = Math.min(valStake/s_total,1.0/a)
  return linearScore
``` 

Working out possible details of @barnabee's proposal: 

1) I propose we stop thinking of maximum per node and use the same calc to define `optimum staked + delegated` per node. 

1) I propose we introduce a new parameter: `multiple_of_optimum_stake_before_penalty`. We then calculate the validator score as follows:
```
  s_minVal = 5  
  s_numVal = numberOfValidators 
  a = Math.max(s_minVal, s_numVal/s_compLevel)
  optStake = s_total / a
  multiple_of_optimum_stake_before_penalty = 1.2
  
  // will be 0 until valStake > optStake then grows linearly
  penaltyFlatAmt = Math.max(0.0, valStake-optStake)
  
  // will be 0 until valStake > multiple_of_optimum_stake_before_penalty x optStake then grows linearly
  penaltyDownAmt = Math.max(0.0, valStake-multiple_of_optimum_stake_before_penalty*optStake)
  linearScore = (valStake - penaltyFlatAmt - penaltyDownAmt)/s_total
```

This means the penalty applies in stages: once past optimum (which comes from `comp_level` their score stops growing. Then at a later point it starts decreasing linearly:
![image](https://user-images.githubusercontent.com/62546419/140529137-ebe7cf13-3821-4d1d-8ad2-9b12ddfbc72b.png)


@Vegaklaus The point you make is valid but I would argue that it's equivalent to not being able to delegate the full amount under your management. In our current design some of tokens you manage earn full amount but the ones you've not delegated earn nothing. In the proposed design all tokens are earning, just a bit less. 

I'd argue that Barney's proposal leads to much simpler user experience without compromising any significant design goal.

**Comment by davidsiska-vega** [comment]
Note that ☝️ the graph is done under assumption that tokens are being added to the system so the bit that would be flat in the graph if people are just shuffling nominations is sloping up (but less than the earlier period).

**Comment by Vegaklaus** [comment]
It's slightly different in that the drop in revenue can hit you at any time, while in the current version once you delegate, you're good. At least for startup (where we can assure everyone gets what they need), the validators where pretty worried that their customers get a less than perfect deal.

**Comment by Vegaklaus** [comment]
The hard break was mostly added because of those discussions

**Comment by davidsiska-vega** [comment]
ad 1. I'd argue that if you delegate it shouldn't mean you can park your tokens, take no actions and expect guaranteed income. In fact I'd say it's preferable if your revenue can drop randomly because you've nominated sub-optimal validator. You're then incentivised to go to the UI and interact with the protocol (maybe you'll spot a governance proposal you want to vote on while you're there). 

ad 2. I really don't think we should be designing our protocol around some deals that some exchanges and custody providers have with various validating outfits. 

We should decide what's right. We should document it well. We should let all parties interact with the system (and yes there may be times when it sucks to be them).

**Comment by Vegaklaus** [comment]
I also wouldn't like to lose an exchange because they think it's too much work to manage us (and exchanges getting active community participants will likely be a long way). My feeling is that all this comes from some misunderstandings - exchanges are used to requiring their preferred partner and have special contracts in place because most chains have slashing, and as an custodian you don't want to risk losing your customers tokens because of a bad validator. We don't have that so they shouldn't have a problem with that in our case, but it's what they're used to.
I'm personally happy to drop the limit, I'm just nor sure yet we're in a position where we can say 'Sucks to be you' without risking that in the end it sucks to be us.

**Comment by barnabee** [comment]
Agree with David that staking shouldn’t be risk free. You have a role as staked. You can either risk getting paid a bit less or pay attention.

I also agree that I’m not sure that exchanges/custodians/staking providers and their contracts should be our concern in the mechanism design, though we do want to minimally be able to offer something that is workable for Coinlist in the first few months at least. But I’m not sure the current design does that any better (it’s really the params we’re setting that make it work for them as far as I can tell) and I think in the long term theee exchanges et al. will need to help themselves:

- More will join all the time, if they are large there’s a significant chance their stake will be rejected, it’s not like solving this problem for Coinlist on day one makes it go away
- it’s quite possible, especially when we add more validators that too many of them sign contracts with the same validator for them all to be allowed to stake under our current model, with the change at least they can get some reward while they renegotiate their contracts 
- We can use parameters and governance to configure it to be very permissive to start with if we want to allow them all to execute their contracts and get full rewards — this can be done whatever answer we pick and we already have to do it with the current version, so it’s not like the solution we have solves exchange/custodian issues if we set the parameters we’d ideally like, we’re just configuring it to let validators get too big if needed as far as I can see?

So if it’s only the exchange argument I think it is probably fine to change [back] to capped rewards rather than rejected staking, as long as we can configure how aggressive that is so early on they will all be ok.

Would like @MM0819 opinion though before we commit though
