### ISSUE TITLE
Review LNL spec in relation to Vega Core bug: 4460

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#760]
https://github.com/vegaprotocol/vega/issues/4460

During discussions between Zohar and David it was agreed that the spec needed reviewing in relation to the above bug.

Once this has been reviewed the bug can either be prioritised or closed accordingly

**Comment by davidsiska-vega** [comment]
@barnabee having read the issue https://github.com/vegaprotocol/vega/issues/4460  do you feel that LNL checkpoints should behave differently? We could arguably change the spec so that it saves / restores all active proposals (market / asset / governance) and all votes by all parties. This is more data to store and LNL philosophy has been to keep everything *minimal*. 

However losing all votes etc. during a LNL restore is a pain, having seen how hard it is to get people to vote in the first place.

**Comment by gordsport** [comment]
@EVODelavega - as you have resolved the bug (see linked chain of bug fixes) can you correct/update the spec accordingly

**Comment by gordsport** [comment]
Hey @jeremyletang, with the improvements in checkpoints implemented recently is this issue (and related bug) still something we need to review in terms of the spec update and any resulting work?
