### ISSUE TITLE
Create a specification for market governance proposals

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#774]
In order to be able to begin work on the market governance proposals we need a specification with acceptance criteria for how market parameters can be changed via governance (e.g. weighting by LP shares, granular difficulty control).

**Comment by davidsiska-vega** [comment]
Some thoughts to kick this off. Broadly we can have the following vote on a market:
1) LPs either by stake or by equity-like share
2) All parties with margin locked on a market (for LPs I'd add margin + bond) 
3) All governance token holdes aka vega token holders.

There are issues with all of those but the main ones for me are
Three) Why would a token holder care about a specific market and its parameters? How to drive genuine participation? I think governance this way will be very clunky.

One) Here the problem is more subtle: let's say I can change an oracle thanks to my bond size or equity like share. So I propose a market and have token holders vote (it's a good market with a trusted oracle). Market launches. Now I get the oracle changed through governance to something dodgy. This is not so much an issue now but soon(TM) we will support ethereum oracles so I can set the oracle to be the Uniswap market price for ETH/USD pool (very solid, all token holders approve) but then I change it later to something dodgy.

Two) This is rather volatile as it's hanging on the margin balance. Of course we could do some exponentially weighted averages but then the vote mechanics are more complicated to implement. Also I can open a position (long) with party A I control with party B I control I go short now I have a lot of margin deployed, I change the oracle or something else, I close my positions and let others suffer.

**Comment by davidsiska-vega** [comment]
Four) Vote initiated by anyone with enough VEGA. LPs vote by either bond or equity like share. In parallel VEGA token holders can vote. If participation threshold for token holders is met then it is their decision that counts.

**Comment by barnabee** [comment]
Personally I think 3 is a non-starter. It feels to me like it would be similar to not doing it, unless the threshold is so low that a malicious entity can easily acquire tokens and screw with a market.

I initially thought **LPs voting by equity like share** was the best option (and _maybe_) still do because in general that means the early creators and those who profit most froma succesful market with trading have the most weight. This makes a lot of sense but _could_ break down if a market has a "down round" in which it becomes cheap to acquire equity like share and fuck with a markert. I can't remember what (if any) limits/minimums we have in place here. If we don't have any, perhaps we could add some to address this, something like bounding the "valuation" by the total stake deployed at the lower end (I know we talked about something similar, just can't remember if we went with it). If we could get comfortable with mitigation of that risk I think this is still my preferred option.

Other than that I think **all participants by bond + margin account balance** is probably the other decent option, perhaps lowest margin account balance over the past X seconds / epoch, and possibly allowing to apply some nultiplier to bond account balance so it counts for more. 

In any case, I would suggest you need to have both (a) the normal governance threshold of Vega; and (b) a non-zero voting weight for your proposal in order to make a market proposal.

**Comment by davidsiska-vega** [comment]
Agreements from the call: 
- LPs vote by equity-like share (min eq.-like-share to propose + min vega). In parallel a VEGA token holders vote. If a participation threshold and majority rules are met then the VEGA token holders can push the proposal to push through or cancel. 

- Any market parameters can be changed apart from settlement asset. If core thinks certain changes will be harder to action then we can make those immutable too (in the full spec PR). The proposal is either a re-submission of all parameters or a format that allows multiple changes. Same format as what goes for market proposal with only parameters that are being changed being populated. @jeremyletang says it's easier to re-submit everything.

**Comment by davidsiska-vega** [comment]
Immutable stuff:
- can't change id (doh)
- can't change name  and short code
- can't change settlement asset 
- can't change market decimal places
