### ISSUE TITLE
Defect on LP provider margin/general/bond account 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/specs#941]
[https://github.com/vegaprotocol/specs-internal/blob/lp-fees-test/qa-scenarios/liquidity-provision-bond-account.feature]

The margin/general/bond account for LP provider "party0" is wrong at line 183.

-    With additional order at line 154, and party0 repeg the lp order: vol 15 on price 1000, vol 90 on price 1020
-    party0 margin should be mark_price x order_size x rf_short = 1000 x (90 + 15) x 3.5569036 = 373475
-    initial margin level is 373475*1.2=448170
-    so party0 should have 448170 in margin account, and 450000-448170=1830 in general account, and 50000 in bond account

**Comment by gordsport** [comment]
Once fixed this needs to move to the vega repo

**Comment by Jiajia-Cui** [comment]
I think I can replicate the current (wrong) margin account calculation, which is using the previous order vol (short order vol 106 at price 1020 +  additional order at line 156 (vol 15 at price 1000);  instead of the using the updated repeged order ( vol 15 at price 1000 + vol 90 at price 1020) ....hence the margin account on line 186 is over the correct  margin

**Comment by EVODelavega** [comment]
OK, as far as vega (core) is concerned, this ties in with [issue #4627](https://github.com/vegaprotocol/vega/issues/4627):

When an LP submits a new order, we recalculate the margin requirements as we do for any order. At this point, we don't care if the party is an LP or not. We work out the margin requirements assuming whatever position the party holds stays the same. If the margin requirement increases, we try and top up the margin balance to the initial margin level. If this means dipping in to the bond account, we slash the bond account and apply a penalty.

This newly submitted order will change the LP orders/shapes, so we cancel the orders currently on the book, and replace them with new ones. In doing so, we check the margin requirements as we submit the new orders. In this particular case, the party had buy and sell orders (potential long/short) on the book the book like this: sell 106@1020, buy 109@970. The party submitted a sell order of 15@1000. This meant that their worst potential short (and the position we based the margin calculation on) was short 121@(15000+108120)/121 (≃1017.5).

The sell LP order was updated to sell 90@1020 (potential short becoming 105@(15000+91800)/105 (≃1017.1). The margin requirement drops, but the release level remains above the margin balance. Because the margin requirement when the sell order for 15@1000 was submitted caused the margin balance to go up to 500000, we didn't release any of the balance later on. The initial margin level dropped down to 448170, but the release level was higher than the margin account balance still.

The upshot is that seemingly, we transferred too much to the margin account, because briefly (between placing the new order and repricing the LP orders), that was the balance required.
